// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: cycles.sql

package db

import (
	"context"
)

const countCycles = `-- name: CountCycles :one
SELECT COUNT(*) FROM cycles
`

func (q *Queries) CountCycles(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countCycles)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countWeeksByCycleID = `-- name: CountWeeksByCycleID :one
SELECT COUNT(*) FROM weeks WHERE cycle_id = ?
`

func (q *Queries) CountWeeksByCycleID(ctx context.Context, cycleID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countWeeksByCycleID, cycleID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createCycle = `-- name: CreateCycle :exec
INSERT INTO cycles (id, name, length_weeks, created_at, updated_at)
VALUES (?, ?, ?, ?, ?)
`

type CreateCycleParams struct {
	ID          string `json:"id"`
	Name        string `json:"name"`
	LengthWeeks int64  `json:"length_weeks"`
	CreatedAt   string `json:"created_at"`
	UpdatedAt   string `json:"updated_at"`
}

func (q *Queries) CreateCycle(ctx context.Context, arg CreateCycleParams) error {
	_, err := q.db.ExecContext(ctx, createCycle,
		arg.ID,
		arg.Name,
		arg.LengthWeeks,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const cycleIsUsedByPrograms = `-- name: CycleIsUsedByPrograms :one
SELECT EXISTS(
    SELECT 1 FROM programs p
    WHERE p.cycle_id = ?
) AS is_used
`

func (q *Queries) CycleIsUsedByPrograms(ctx context.Context, cycleID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, cycleIsUsedByPrograms, cycleID)
	var is_used int64
	err := row.Scan(&is_used)
	return is_used, err
}

const deleteCycle = `-- name: DeleteCycle :exec
DELETE FROM cycles WHERE id = ?
`

func (q *Queries) DeleteCycle(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteCycle, id)
	return err
}

const getCycle = `-- name: GetCycle :one
SELECT id, name, length_weeks, created_at, updated_at
FROM cycles
WHERE id = ?
`

func (q *Queries) GetCycle(ctx context.Context, id string) (Cycle, error) {
	row := q.db.QueryRowContext(ctx, getCycle, id)
	var i Cycle
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.LengthWeeks,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCyclesByCreatedAtAsc = `-- name: ListCyclesByCreatedAtAsc :many
SELECT id, name, length_weeks, created_at, updated_at
FROM cycles
ORDER BY created_at ASC
LIMIT ? OFFSET ?
`

type ListCyclesByCreatedAtAscParams struct {
	Limit  int64 `json:"limit"`
	Offset int64 `json:"offset"`
}

func (q *Queries) ListCyclesByCreatedAtAsc(ctx context.Context, arg ListCyclesByCreatedAtAscParams) ([]Cycle, error) {
	rows, err := q.db.QueryContext(ctx, listCyclesByCreatedAtAsc, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Cycle{}
	for rows.Next() {
		var i Cycle
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.LengthWeeks,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCyclesByCreatedAtDesc = `-- name: ListCyclesByCreatedAtDesc :many
SELECT id, name, length_weeks, created_at, updated_at
FROM cycles
ORDER BY created_at DESC
LIMIT ? OFFSET ?
`

type ListCyclesByCreatedAtDescParams struct {
	Limit  int64 `json:"limit"`
	Offset int64 `json:"offset"`
}

func (q *Queries) ListCyclesByCreatedAtDesc(ctx context.Context, arg ListCyclesByCreatedAtDescParams) ([]Cycle, error) {
	rows, err := q.db.QueryContext(ctx, listCyclesByCreatedAtDesc, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Cycle{}
	for rows.Next() {
		var i Cycle
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.LengthWeeks,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCyclesByLengthWeeksAsc = `-- name: ListCyclesByLengthWeeksAsc :many
SELECT id, name, length_weeks, created_at, updated_at
FROM cycles
ORDER BY length_weeks ASC
LIMIT ? OFFSET ?
`

type ListCyclesByLengthWeeksAscParams struct {
	Limit  int64 `json:"limit"`
	Offset int64 `json:"offset"`
}

func (q *Queries) ListCyclesByLengthWeeksAsc(ctx context.Context, arg ListCyclesByLengthWeeksAscParams) ([]Cycle, error) {
	rows, err := q.db.QueryContext(ctx, listCyclesByLengthWeeksAsc, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Cycle{}
	for rows.Next() {
		var i Cycle
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.LengthWeeks,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCyclesByLengthWeeksDesc = `-- name: ListCyclesByLengthWeeksDesc :many
SELECT id, name, length_weeks, created_at, updated_at
FROM cycles
ORDER BY length_weeks DESC
LIMIT ? OFFSET ?
`

type ListCyclesByLengthWeeksDescParams struct {
	Limit  int64 `json:"limit"`
	Offset int64 `json:"offset"`
}

func (q *Queries) ListCyclesByLengthWeeksDesc(ctx context.Context, arg ListCyclesByLengthWeeksDescParams) ([]Cycle, error) {
	rows, err := q.db.QueryContext(ctx, listCyclesByLengthWeeksDesc, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Cycle{}
	for rows.Next() {
		var i Cycle
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.LengthWeeks,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCyclesByNameAsc = `-- name: ListCyclesByNameAsc :many
SELECT id, name, length_weeks, created_at, updated_at
FROM cycles
ORDER BY name ASC
LIMIT ? OFFSET ?
`

type ListCyclesByNameAscParams struct {
	Limit  int64 `json:"limit"`
	Offset int64 `json:"offset"`
}

func (q *Queries) ListCyclesByNameAsc(ctx context.Context, arg ListCyclesByNameAscParams) ([]Cycle, error) {
	rows, err := q.db.QueryContext(ctx, listCyclesByNameAsc, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Cycle{}
	for rows.Next() {
		var i Cycle
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.LengthWeeks,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCyclesByNameDesc = `-- name: ListCyclesByNameDesc :many
SELECT id, name, length_weeks, created_at, updated_at
FROM cycles
ORDER BY name DESC
LIMIT ? OFFSET ?
`

type ListCyclesByNameDescParams struct {
	Limit  int64 `json:"limit"`
	Offset int64 `json:"offset"`
}

func (q *Queries) ListCyclesByNameDesc(ctx context.Context, arg ListCyclesByNameDescParams) ([]Cycle, error) {
	rows, err := q.db.QueryContext(ctx, listCyclesByNameDesc, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Cycle{}
	for rows.Next() {
		var i Cycle
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.LengthWeeks,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWeeksByCycleID = `-- name: ListWeeksByCycleID :many
SELECT id, week_number, variant, cycle_id, created_at, updated_at
FROM weeks
WHERE cycle_id = ?
ORDER BY week_number ASC
`

func (q *Queries) ListWeeksByCycleID(ctx context.Context, cycleID string) ([]Week, error) {
	rows, err := q.db.QueryContext(ctx, listWeeksByCycleID, cycleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Week{}
	for rows.Next() {
		var i Week
		if err := rows.Scan(
			&i.ID,
			&i.WeekNumber,
			&i.Variant,
			&i.CycleID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCycle = `-- name: UpdateCycle :exec
UPDATE cycles
SET name = ?, length_weeks = ?, updated_at = ?
WHERE id = ?
`

type UpdateCycleParams struct {
	Name        string `json:"name"`
	LengthWeeks int64  `json:"length_weeks"`
	UpdatedAt   string `json:"updated_at"`
	ID          string `json:"id"`
}

func (q *Queries) UpdateCycle(ctx context.Context, arg UpdateCycleParams) error {
	_, err := q.db.ExecContext(ctx, updateCycle,
		arg.Name,
		arg.LengthWeeks,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}
