// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: daily_lookups.sql

package db

import (
	"context"
	"database/sql"
)

const countDailyLookups = `-- name: CountDailyLookups :one
SELECT COUNT(*) FROM daily_lookups
`

func (q *Queries) CountDailyLookups(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countDailyLookups)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createDailyLookup = `-- name: CreateDailyLookup :exec
INSERT INTO daily_lookups (id, name, entries, program_id, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?)
`

type CreateDailyLookupParams struct {
	ID        string         `json:"id"`
	Name      string         `json:"name"`
	Entries   string         `json:"entries"`
	ProgramID sql.NullString `json:"program_id"`
	CreatedAt string         `json:"created_at"`
	UpdatedAt string         `json:"updated_at"`
}

func (q *Queries) CreateDailyLookup(ctx context.Context, arg CreateDailyLookupParams) error {
	_, err := q.db.ExecContext(ctx, createDailyLookup,
		arg.ID,
		arg.Name,
		arg.Entries,
		arg.ProgramID,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const dailyLookupIsUsedByPrograms = `-- name: DailyLookupIsUsedByPrograms :one
SELECT EXISTS(
    SELECT 1 FROM programs p
    WHERE p.daily_lookup_id = ?
) AS is_used
`

func (q *Queries) DailyLookupIsUsedByPrograms(ctx context.Context, dailyLookupID sql.NullString) (int64, error) {
	row := q.db.QueryRowContext(ctx, dailyLookupIsUsedByPrograms, dailyLookupID)
	var is_used int64
	err := row.Scan(&is_used)
	return is_used, err
}

const deleteDailyLookup = `-- name: DeleteDailyLookup :exec
DELETE FROM daily_lookups WHERE id = ?
`

func (q *Queries) DeleteDailyLookup(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteDailyLookup, id)
	return err
}

const getDailyLookup = `-- name: GetDailyLookup :one
SELECT id, name, entries, program_id, created_at, updated_at
FROM daily_lookups
WHERE id = ?
`

func (q *Queries) GetDailyLookup(ctx context.Context, id string) (DailyLookup, error) {
	row := q.db.QueryRowContext(ctx, getDailyLookup, id)
	var i DailyLookup
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Entries,
		&i.ProgramID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listDailyLookupsByCreatedAtAsc = `-- name: ListDailyLookupsByCreatedAtAsc :many
SELECT id, name, entries, program_id, created_at, updated_at
FROM daily_lookups
ORDER BY created_at ASC
LIMIT ? OFFSET ?
`

type ListDailyLookupsByCreatedAtAscParams struct {
	Limit  int64 `json:"limit"`
	Offset int64 `json:"offset"`
}

func (q *Queries) ListDailyLookupsByCreatedAtAsc(ctx context.Context, arg ListDailyLookupsByCreatedAtAscParams) ([]DailyLookup, error) {
	rows, err := q.db.QueryContext(ctx, listDailyLookupsByCreatedAtAsc, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DailyLookup{}
	for rows.Next() {
		var i DailyLookup
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Entries,
			&i.ProgramID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDailyLookupsByCreatedAtDesc = `-- name: ListDailyLookupsByCreatedAtDesc :many
SELECT id, name, entries, program_id, created_at, updated_at
FROM daily_lookups
ORDER BY created_at DESC
LIMIT ? OFFSET ?
`

type ListDailyLookupsByCreatedAtDescParams struct {
	Limit  int64 `json:"limit"`
	Offset int64 `json:"offset"`
}

func (q *Queries) ListDailyLookupsByCreatedAtDesc(ctx context.Context, arg ListDailyLookupsByCreatedAtDescParams) ([]DailyLookup, error) {
	rows, err := q.db.QueryContext(ctx, listDailyLookupsByCreatedAtDesc, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DailyLookup{}
	for rows.Next() {
		var i DailyLookup
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Entries,
			&i.ProgramID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDailyLookupsByNameAsc = `-- name: ListDailyLookupsByNameAsc :many
SELECT id, name, entries, program_id, created_at, updated_at
FROM daily_lookups
ORDER BY name ASC
LIMIT ? OFFSET ?
`

type ListDailyLookupsByNameAscParams struct {
	Limit  int64 `json:"limit"`
	Offset int64 `json:"offset"`
}

func (q *Queries) ListDailyLookupsByNameAsc(ctx context.Context, arg ListDailyLookupsByNameAscParams) ([]DailyLookup, error) {
	rows, err := q.db.QueryContext(ctx, listDailyLookupsByNameAsc, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DailyLookup{}
	for rows.Next() {
		var i DailyLookup
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Entries,
			&i.ProgramID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDailyLookupsByNameDesc = `-- name: ListDailyLookupsByNameDesc :many
SELECT id, name, entries, program_id, created_at, updated_at
FROM daily_lookups
ORDER BY name DESC
LIMIT ? OFFSET ?
`

type ListDailyLookupsByNameDescParams struct {
	Limit  int64 `json:"limit"`
	Offset int64 `json:"offset"`
}

func (q *Queries) ListDailyLookupsByNameDesc(ctx context.Context, arg ListDailyLookupsByNameDescParams) ([]DailyLookup, error) {
	rows, err := q.db.QueryContext(ctx, listDailyLookupsByNameDesc, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DailyLookup{}
	for rows.Next() {
		var i DailyLookup
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Entries,
			&i.ProgramID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDailyLookup = `-- name: UpdateDailyLookup :exec
UPDATE daily_lookups
SET name = ?, entries = ?, program_id = ?, updated_at = ?
WHERE id = ?
`

type UpdateDailyLookupParams struct {
	Name      string         `json:"name"`
	Entries   string         `json:"entries"`
	ProgramID sql.NullString `json:"program_id"`
	UpdatedAt string         `json:"updated_at"`
	ID        string         `json:"id"`
}

func (q *Queries) UpdateDailyLookup(ctx context.Context, arg UpdateDailyLookupParams) error {
	_, err := q.db.ExecContext(ctx, updateDailyLookup,
		arg.Name,
		arg.Entries,
		arg.ProgramID,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}
