// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
)

type Cycle struct {
	ID          string `json:"id"`
	Name        string `json:"name"`
	LengthWeeks int64  `json:"length_weeks"`
	CreatedAt   string `json:"created_at"`
	UpdatedAt   string `json:"updated_at"`
}

type DailyLookup struct {
	ID        string         `json:"id"`
	Name      string         `json:"name"`
	Entries   string         `json:"entries"`
	ProgramID sql.NullString `json:"program_id"`
	CreatedAt string         `json:"created_at"`
	UpdatedAt string         `json:"updated_at"`
}

type Day struct {
	ID        string         `json:"id"`
	Name      string         `json:"name"`
	Slug      string         `json:"slug"`
	Metadata  sql.NullString `json:"metadata"`
	ProgramID sql.NullString `json:"program_id"`
	CreatedAt string         `json:"created_at"`
	UpdatedAt string         `json:"updated_at"`
}

type DayPrescription struct {
	ID             string `json:"id"`
	DayID          string `json:"day_id"`
	PrescriptionID string `json:"prescription_id"`
	Order          int64  `json:"order"`
	CreatedAt      string `json:"created_at"`
}

type FailureCounter struct {
	ID                  string         `json:"id"`
	UserID              string         `json:"user_id"`
	LiftID              string         `json:"lift_id"`
	ProgressionID       string         `json:"progression_id"`
	ConsecutiveFailures int64          `json:"consecutive_failures"`
	LastFailureAt       sql.NullString `json:"last_failure_at"`
	LastSuccessAt       sql.NullString `json:"last_success_at"`
	CreatedAt           string         `json:"created_at"`
	UpdatedAt           string         `json:"updated_at"`
}

type Lift struct {
	ID                string         `json:"id"`
	Name              string         `json:"name"`
	Slug              string         `json:"slug"`
	IsCompetitionLift int64          `json:"is_competition_lift"`
	ParentLiftID      sql.NullString `json:"parent_lift_id"`
	CreatedAt         string         `json:"created_at"`
	UpdatedAt         string         `json:"updated_at"`
}

type LiftMax struct {
	ID            string  `json:"id"`
	UserID        string  `json:"user_id"`
	LiftID        string  `json:"lift_id"`
	Type          string  `json:"type"`
	Value         float64 `json:"value"`
	EffectiveDate string  `json:"effective_date"`
	CreatedAt     string  `json:"created_at"`
	UpdatedAt     string  `json:"updated_at"`
}

type LoggedSet struct {
	ID             string          `json:"id"`
	UserID         string          `json:"user_id"`
	SessionID      string          `json:"session_id"`
	PrescriptionID string          `json:"prescription_id"`
	LiftID         string          `json:"lift_id"`
	SetNumber      int64           `json:"set_number"`
	Weight         float64         `json:"weight"`
	TargetReps     int64           `json:"target_reps"`
	RepsPerformed  int64           `json:"reps_performed"`
	IsAmrap        bool            `json:"is_amrap"`
	CreatedAt      string          `json:"created_at"`
	Rpe            sql.NullFloat64 `json:"rpe"`
}

type Prescription struct {
	ID           string         `json:"id"`
	LiftID       string         `json:"lift_id"`
	LoadStrategy string         `json:"load_strategy"`
	SetScheme    string         `json:"set_scheme"`
	Order        int64          `json:"order"`
	Notes        sql.NullString `json:"notes"`
	RestSeconds  sql.NullInt64  `json:"rest_seconds"`
	CreatedAt    string         `json:"created_at"`
	UpdatedAt    string         `json:"updated_at"`
}

type Program struct {
	ID              string          `json:"id"`
	Name            string          `json:"name"`
	Slug            string          `json:"slug"`
	Description     sql.NullString  `json:"description"`
	CycleID         string          `json:"cycle_id"`
	WeeklyLookupID  sql.NullString  `json:"weekly_lookup_id"`
	DailyLookupID   sql.NullString  `json:"daily_lookup_id"`
	DefaultRounding sql.NullFloat64 `json:"default_rounding"`
	CreatedAt       string          `json:"created_at"`
	UpdatedAt       string          `json:"updated_at"`
}

type ProgramProgression struct {
	ID                string          `json:"id"`
	ProgramID         string          `json:"program_id"`
	ProgressionID     string          `json:"progression_id"`
	LiftID            sql.NullString  `json:"lift_id"`
	Priority          int64           `json:"priority"`
	Enabled           int64           `json:"enabled"`
	OverrideIncrement sql.NullFloat64 `json:"override_increment"`
	CreatedAt         string          `json:"created_at"`
	UpdatedAt         string          `json:"updated_at"`
}

type Progression struct {
	ID         string `json:"id"`
	Name       string `json:"name"`
	Type       string `json:"type"`
	Parameters string `json:"parameters"`
	CreatedAt  string `json:"created_at"`
	UpdatedAt  string `json:"updated_at"`
}

type ProgressionLog struct {
	ID             string         `json:"id"`
	UserID         string         `json:"user_id"`
	ProgressionID  string         `json:"progression_id"`
	LiftID         string         `json:"lift_id"`
	PreviousValue  float64        `json:"previous_value"`
	NewValue       float64        `json:"new_value"`
	Delta          float64        `json:"delta"`
	TriggerType    string         `json:"trigger_type"`
	TriggerContext sql.NullString `json:"trigger_context"`
	AppliedAt      string         `json:"applied_at"`
}

type RotationLookup struct {
	ID        string         `json:"id"`
	Name      string         `json:"name"`
	Entries   string         `json:"entries"`
	ProgramID sql.NullString `json:"program_id"`
	CreatedAt string         `json:"created_at"`
	UpdatedAt string         `json:"updated_at"`
}

type User struct {
	ID        string `json:"id"`
	CreatedAt string `json:"created_at"`
	UpdatedAt string `json:"updated_at"`
}

type UserProgramState struct {
	ID                    string         `json:"id"`
	UserID                string         `json:"user_id"`
	ProgramID             string         `json:"program_id"`
	CurrentWeek           int64          `json:"current_week"`
	CurrentCycleIteration int64          `json:"current_cycle_iteration"`
	CurrentDayIndex       sql.NullInt64  `json:"current_day_index"`
	EnrolledAt            string         `json:"enrolled_at"`
	UpdatedAt             string         `json:"updated_at"`
	RotationPosition      int64          `json:"rotation_position"`
	CyclesSinceStart      int64          `json:"cycles_since_start"`
	MeetDate              sql.NullString `json:"meet_date"`
	ScheduleType          sql.NullString `json:"schedule_type"`
}

type UserProgressionState struct {
	ID            string         `json:"id"`
	UserID        string         `json:"user_id"`
	LiftID        string         `json:"lift_id"`
	ProgressionID string         `json:"progression_id"`
	CurrentStage  int64          `json:"current_stage"`
	StateData     sql.NullString `json:"state_data"`
	CreatedAt     string         `json:"created_at"`
	UpdatedAt     string         `json:"updated_at"`
}

type Week struct {
	ID         string         `json:"id"`
	WeekNumber int64          `json:"week_number"`
	Variant    sql.NullString `json:"variant"`
	CycleID    string         `json:"cycle_id"`
	CreatedAt  string         `json:"created_at"`
	UpdatedAt  string         `json:"updated_at"`
}

type WeekDay struct {
	ID        string `json:"id"`
	WeekID    string `json:"week_id"`
	DayID     string `json:"day_id"`
	DayOfWeek string `json:"day_of_week"`
	CreatedAt string `json:"created_at"`
}

type WeeklyLookup struct {
	ID        string         `json:"id"`
	Name      string         `json:"name"`
	Entries   string         `json:"entries"`
	ProgramID sql.NullString `json:"program_id"`
	CreatedAt string         `json:"created_at"`
	UpdatedAt string         `json:"updated_at"`
}
