// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
)

type Lift struct {
	ID                string         `json:"id"`
	Name              string         `json:"name"`
	Slug              string         `json:"slug"`
	IsCompetitionLift int64          `json:"is_competition_lift"`
	ParentLiftID      sql.NullString `json:"parent_lift_id"`
	CreatedAt         string         `json:"created_at"`
	UpdatedAt         string         `json:"updated_at"`
}

type LiftMax struct {
	ID            string  `json:"id"`
	UserID        string  `json:"user_id"`
	LiftID        string  `json:"lift_id"`
	Type          string  `json:"type"`
	Value         float64 `json:"value"`
	EffectiveDate string  `json:"effective_date"`
	CreatedAt     string  `json:"created_at"`
	UpdatedAt     string  `json:"updated_at"`
}

type User struct {
	ID        string `json:"id"`
	CreatedAt string `json:"created_at"`
	UpdatedAt string `json:"updated_at"`
}
