// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: prescriptions.sql

package db

import (
	"context"
	"database/sql"
)

const countPrescriptions = `-- name: CountPrescriptions :one
SELECT COUNT(*) FROM prescriptions
`

func (q *Queries) CountPrescriptions(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countPrescriptions)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countPrescriptionsFilterLift = `-- name: CountPrescriptionsFilterLift :one
SELECT COUNT(*) FROM prescriptions WHERE lift_id = ?
`

func (q *Queries) CountPrescriptionsFilterLift(ctx context.Context, liftID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countPrescriptionsFilterLift, liftID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createPrescription = `-- name: CreatePrescription :exec
INSERT INTO prescriptions (id, lift_id, load_strategy, set_scheme, "order", notes, rest_seconds, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreatePrescriptionParams struct {
	ID           string         `json:"id"`
	LiftID       string         `json:"lift_id"`
	LoadStrategy string         `json:"load_strategy"`
	SetScheme    string         `json:"set_scheme"`
	Order        int64          `json:"order"`
	Notes        sql.NullString `json:"notes"`
	RestSeconds  sql.NullInt64  `json:"rest_seconds"`
	CreatedAt    string         `json:"created_at"`
	UpdatedAt    string         `json:"updated_at"`
}

func (q *Queries) CreatePrescription(ctx context.Context, arg CreatePrescriptionParams) error {
	_, err := q.db.ExecContext(ctx, createPrescription,
		arg.ID,
		arg.LiftID,
		arg.LoadStrategy,
		arg.SetScheme,
		arg.Order,
		arg.Notes,
		arg.RestSeconds,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const deletePrescription = `-- name: DeletePrescription :exec
DELETE FROM prescriptions WHERE id = ?
`

func (q *Queries) DeletePrescription(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deletePrescription, id)
	return err
}

const getPrescription = `-- name: GetPrescription :one
SELECT id, lift_id, load_strategy, set_scheme, "order", notes, rest_seconds, created_at, updated_at
FROM prescriptions
WHERE id = ?
`

func (q *Queries) GetPrescription(ctx context.Context, id string) (Prescription, error) {
	row := q.db.QueryRowContext(ctx, getPrescription, id)
	var i Prescription
	err := row.Scan(
		&i.ID,
		&i.LiftID,
		&i.LoadStrategy,
		&i.SetScheme,
		&i.Order,
		&i.Notes,
		&i.RestSeconds,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const liftHasPrescriptionReferences = `-- name: LiftHasPrescriptionReferences :one
SELECT EXISTS(SELECT 1 FROM prescriptions WHERE lift_id = ?) AS has_references
`

func (q *Queries) LiftHasPrescriptionReferences(ctx context.Context, liftID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, liftHasPrescriptionReferences, liftID)
	var has_references int64
	err := row.Scan(&has_references)
	return has_references, err
}

const listPrescriptionsByCreatedAtAsc = `-- name: ListPrescriptionsByCreatedAtAsc :many
SELECT id, lift_id, load_strategy, set_scheme, "order", notes, rest_seconds, created_at, updated_at
FROM prescriptions
ORDER BY created_at ASC
LIMIT ? OFFSET ?
`

type ListPrescriptionsByCreatedAtAscParams struct {
	Limit  int64 `json:"limit"`
	Offset int64 `json:"offset"`
}

func (q *Queries) ListPrescriptionsByCreatedAtAsc(ctx context.Context, arg ListPrescriptionsByCreatedAtAscParams) ([]Prescription, error) {
	rows, err := q.db.QueryContext(ctx, listPrescriptionsByCreatedAtAsc, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Prescription{}
	for rows.Next() {
		var i Prescription
		if err := rows.Scan(
			&i.ID,
			&i.LiftID,
			&i.LoadStrategy,
			&i.SetScheme,
			&i.Order,
			&i.Notes,
			&i.RestSeconds,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPrescriptionsByCreatedAtDesc = `-- name: ListPrescriptionsByCreatedAtDesc :many
SELECT id, lift_id, load_strategy, set_scheme, "order", notes, rest_seconds, created_at, updated_at
FROM prescriptions
ORDER BY created_at DESC
LIMIT ? OFFSET ?
`

type ListPrescriptionsByCreatedAtDescParams struct {
	Limit  int64 `json:"limit"`
	Offset int64 `json:"offset"`
}

func (q *Queries) ListPrescriptionsByCreatedAtDesc(ctx context.Context, arg ListPrescriptionsByCreatedAtDescParams) ([]Prescription, error) {
	rows, err := q.db.QueryContext(ctx, listPrescriptionsByCreatedAtDesc, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Prescription{}
	for rows.Next() {
		var i Prescription
		if err := rows.Scan(
			&i.ID,
			&i.LiftID,
			&i.LoadStrategy,
			&i.SetScheme,
			&i.Order,
			&i.Notes,
			&i.RestSeconds,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPrescriptionsByOrderAsc = `-- name: ListPrescriptionsByOrderAsc :many
SELECT id, lift_id, load_strategy, set_scheme, "order", notes, rest_seconds, created_at, updated_at
FROM prescriptions
ORDER BY "order" ASC
LIMIT ? OFFSET ?
`

type ListPrescriptionsByOrderAscParams struct {
	Limit  int64 `json:"limit"`
	Offset int64 `json:"offset"`
}

func (q *Queries) ListPrescriptionsByOrderAsc(ctx context.Context, arg ListPrescriptionsByOrderAscParams) ([]Prescription, error) {
	rows, err := q.db.QueryContext(ctx, listPrescriptionsByOrderAsc, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Prescription{}
	for rows.Next() {
		var i Prescription
		if err := rows.Scan(
			&i.ID,
			&i.LiftID,
			&i.LoadStrategy,
			&i.SetScheme,
			&i.Order,
			&i.Notes,
			&i.RestSeconds,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPrescriptionsByOrderDesc = `-- name: ListPrescriptionsByOrderDesc :many
SELECT id, lift_id, load_strategy, set_scheme, "order", notes, rest_seconds, created_at, updated_at
FROM prescriptions
ORDER BY "order" DESC
LIMIT ? OFFSET ?
`

type ListPrescriptionsByOrderDescParams struct {
	Limit  int64 `json:"limit"`
	Offset int64 `json:"offset"`
}

func (q *Queries) ListPrescriptionsByOrderDesc(ctx context.Context, arg ListPrescriptionsByOrderDescParams) ([]Prescription, error) {
	rows, err := q.db.QueryContext(ctx, listPrescriptionsByOrderDesc, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Prescription{}
	for rows.Next() {
		var i Prescription
		if err := rows.Scan(
			&i.ID,
			&i.LiftID,
			&i.LoadStrategy,
			&i.SetScheme,
			&i.Order,
			&i.Notes,
			&i.RestSeconds,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPrescriptionsFilterLiftByCreatedAtAsc = `-- name: ListPrescriptionsFilterLiftByCreatedAtAsc :many
SELECT id, lift_id, load_strategy, set_scheme, "order", notes, rest_seconds, created_at, updated_at
FROM prescriptions
WHERE lift_id = ?
ORDER BY created_at ASC
LIMIT ? OFFSET ?
`

type ListPrescriptionsFilterLiftByCreatedAtAscParams struct {
	LiftID string `json:"lift_id"`
	Limit  int64  `json:"limit"`
	Offset int64  `json:"offset"`
}

func (q *Queries) ListPrescriptionsFilterLiftByCreatedAtAsc(ctx context.Context, arg ListPrescriptionsFilterLiftByCreatedAtAscParams) ([]Prescription, error) {
	rows, err := q.db.QueryContext(ctx, listPrescriptionsFilterLiftByCreatedAtAsc, arg.LiftID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Prescription{}
	for rows.Next() {
		var i Prescription
		if err := rows.Scan(
			&i.ID,
			&i.LiftID,
			&i.LoadStrategy,
			&i.SetScheme,
			&i.Order,
			&i.Notes,
			&i.RestSeconds,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPrescriptionsFilterLiftByCreatedAtDesc = `-- name: ListPrescriptionsFilterLiftByCreatedAtDesc :many
SELECT id, lift_id, load_strategy, set_scheme, "order", notes, rest_seconds, created_at, updated_at
FROM prescriptions
WHERE lift_id = ?
ORDER BY created_at DESC
LIMIT ? OFFSET ?
`

type ListPrescriptionsFilterLiftByCreatedAtDescParams struct {
	LiftID string `json:"lift_id"`
	Limit  int64  `json:"limit"`
	Offset int64  `json:"offset"`
}

func (q *Queries) ListPrescriptionsFilterLiftByCreatedAtDesc(ctx context.Context, arg ListPrescriptionsFilterLiftByCreatedAtDescParams) ([]Prescription, error) {
	rows, err := q.db.QueryContext(ctx, listPrescriptionsFilterLiftByCreatedAtDesc, arg.LiftID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Prescription{}
	for rows.Next() {
		var i Prescription
		if err := rows.Scan(
			&i.ID,
			&i.LiftID,
			&i.LoadStrategy,
			&i.SetScheme,
			&i.Order,
			&i.Notes,
			&i.RestSeconds,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPrescriptionsFilterLiftByOrderAsc = `-- name: ListPrescriptionsFilterLiftByOrderAsc :many
SELECT id, lift_id, load_strategy, set_scheme, "order", notes, rest_seconds, created_at, updated_at
FROM prescriptions
WHERE lift_id = ?
ORDER BY "order" ASC
LIMIT ? OFFSET ?
`

type ListPrescriptionsFilterLiftByOrderAscParams struct {
	LiftID string `json:"lift_id"`
	Limit  int64  `json:"limit"`
	Offset int64  `json:"offset"`
}

func (q *Queries) ListPrescriptionsFilterLiftByOrderAsc(ctx context.Context, arg ListPrescriptionsFilterLiftByOrderAscParams) ([]Prescription, error) {
	rows, err := q.db.QueryContext(ctx, listPrescriptionsFilterLiftByOrderAsc, arg.LiftID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Prescription{}
	for rows.Next() {
		var i Prescription
		if err := rows.Scan(
			&i.ID,
			&i.LiftID,
			&i.LoadStrategy,
			&i.SetScheme,
			&i.Order,
			&i.Notes,
			&i.RestSeconds,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPrescriptionsFilterLiftByOrderDesc = `-- name: ListPrescriptionsFilterLiftByOrderDesc :many
SELECT id, lift_id, load_strategy, set_scheme, "order", notes, rest_seconds, created_at, updated_at
FROM prescriptions
WHERE lift_id = ?
ORDER BY "order" DESC
LIMIT ? OFFSET ?
`

type ListPrescriptionsFilterLiftByOrderDescParams struct {
	LiftID string `json:"lift_id"`
	Limit  int64  `json:"limit"`
	Offset int64  `json:"offset"`
}

func (q *Queries) ListPrescriptionsFilterLiftByOrderDesc(ctx context.Context, arg ListPrescriptionsFilterLiftByOrderDescParams) ([]Prescription, error) {
	rows, err := q.db.QueryContext(ctx, listPrescriptionsFilterLiftByOrderDesc, arg.LiftID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Prescription{}
	for rows.Next() {
		var i Prescription
		if err := rows.Scan(
			&i.ID,
			&i.LiftID,
			&i.LoadStrategy,
			&i.SetScheme,
			&i.Order,
			&i.Notes,
			&i.RestSeconds,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePrescription = `-- name: UpdatePrescription :exec
UPDATE prescriptions
SET lift_id = ?, load_strategy = ?, set_scheme = ?, "order" = ?, notes = ?, rest_seconds = ?, updated_at = ?
WHERE id = ?
`

type UpdatePrescriptionParams struct {
	LiftID       string         `json:"lift_id"`
	LoadStrategy string         `json:"load_strategy"`
	SetScheme    string         `json:"set_scheme"`
	Order        int64          `json:"order"`
	Notes        sql.NullString `json:"notes"`
	RestSeconds  sql.NullInt64  `json:"rest_seconds"`
	UpdatedAt    string         `json:"updated_at"`
	ID           string         `json:"id"`
}

func (q *Queries) UpdatePrescription(ctx context.Context, arg UpdatePrescriptionParams) error {
	_, err := q.db.ExecContext(ctx, updatePrescription,
		arg.LiftID,
		arg.LoadStrategy,
		arg.SetScheme,
		arg.Order,
		arg.Notes,
		arg.RestSeconds,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}
