// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: programs.sql

package db

import (
	"context"
	"database/sql"
)

const countEnrolledUsers = `-- name: CountEnrolledUsers :one
SELECT COUNT(*) FROM user_program_states WHERE program_id = ?
`

func (q *Queries) CountEnrolledUsers(ctx context.Context, programID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countEnrolledUsers, programID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countPrograms = `-- name: CountPrograms :one
SELECT COUNT(*) FROM programs
`

func (q *Queries) CountPrograms(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countPrograms)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countProgramsFiltered = `-- name: CountProgramsFiltered :one
SELECT COUNT(*) FROM programs
WHERE (?1 IS NULL OR difficulty = ?1)
  AND (?2 IS NULL OR days_per_week = ?2)
  AND (?3 IS NULL OR focus = ?3)
  AND (?4 IS NULL OR has_amrap = ?4)
  AND (?5 IS NULL OR name LIKE '%' || ?5 || '%' COLLATE NOCASE)
`

type CountProgramsFilteredParams struct {
	Difficulty  interface{} `json:"difficulty"`
	DaysPerWeek interface{} `json:"days_per_week"`
	Focus       interface{} `json:"focus"`
	HasAmrap    interface{} `json:"has_amrap"`
	Search      interface{} `json:"search"`
}

func (q *Queries) CountProgramsFiltered(ctx context.Context, arg CountProgramsFilteredParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countProgramsFiltered,
		arg.Difficulty,
		arg.DaysPerWeek,
		arg.Focus,
		arg.HasAmrap,
		arg.Search,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createProgram = `-- name: CreateProgram :exec
INSERT INTO programs (id, name, slug, description, cycle_id, weekly_lookup_id, daily_lookup_id, default_rounding, difficulty, days_per_week, focus, has_amrap, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateProgramParams struct {
	ID              string          `json:"id"`
	Name            string          `json:"name"`
	Slug            string          `json:"slug"`
	Description     sql.NullString  `json:"description"`
	CycleID         string          `json:"cycle_id"`
	WeeklyLookupID  sql.NullString  `json:"weekly_lookup_id"`
	DailyLookupID   sql.NullString  `json:"daily_lookup_id"`
	DefaultRounding sql.NullFloat64 `json:"default_rounding"`
	Difficulty      string          `json:"difficulty"`
	DaysPerWeek     int64           `json:"days_per_week"`
	Focus           string          `json:"focus"`
	HasAmrap        int64           `json:"has_amrap"`
	CreatedAt       string          `json:"created_at"`
	UpdatedAt       string          `json:"updated_at"`
}

func (q *Queries) CreateProgram(ctx context.Context, arg CreateProgramParams) error {
	_, err := q.db.ExecContext(ctx, createProgram,
		arg.ID,
		arg.Name,
		arg.Slug,
		arg.Description,
		arg.CycleID,
		arg.WeeklyLookupID,
		arg.DailyLookupID,
		arg.DefaultRounding,
		arg.Difficulty,
		arg.DaysPerWeek,
		arg.Focus,
		arg.HasAmrap,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const deleteProgram = `-- name: DeleteProgram :exec
DELETE FROM programs WHERE id = ?
`

func (q *Queries) DeleteProgram(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteProgram, id)
	return err
}

const getCycleForProgram = `-- name: GetCycleForProgram :one
SELECT c.id, c.name, c.length_weeks, c.created_at, c.updated_at
FROM cycles c
WHERE c.id = ?
`

func (q *Queries) GetCycleForProgram(ctx context.Context, id string) (Cycle, error) {
	row := q.db.QueryRowContext(ctx, getCycleForProgram, id)
	var i Cycle
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.LengthWeeks,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDailyLookupForProgram = `-- name: GetDailyLookupForProgram :one
SELECT id, name, entries, program_id, created_at, updated_at
FROM daily_lookups
WHERE id = ?
`

func (q *Queries) GetDailyLookupForProgram(ctx context.Context, id string) (DailyLookup, error) {
	row := q.db.QueryRowContext(ctx, getDailyLookupForProgram, id)
	var i DailyLookup
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Entries,
		&i.ProgramID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProgram = `-- name: GetProgram :one
SELECT id, name, slug, description, cycle_id, weekly_lookup_id, daily_lookup_id, default_rounding, difficulty, days_per_week, focus, has_amrap, created_at, updated_at
FROM programs
WHERE id = ?
`

type GetProgramRow struct {
	ID              string          `json:"id"`
	Name            string          `json:"name"`
	Slug            string          `json:"slug"`
	Description     sql.NullString  `json:"description"`
	CycleID         string          `json:"cycle_id"`
	WeeklyLookupID  sql.NullString  `json:"weekly_lookup_id"`
	DailyLookupID   sql.NullString  `json:"daily_lookup_id"`
	DefaultRounding sql.NullFloat64 `json:"default_rounding"`
	Difficulty      string          `json:"difficulty"`
	DaysPerWeek     int64           `json:"days_per_week"`
	Focus           string          `json:"focus"`
	HasAmrap        int64           `json:"has_amrap"`
	CreatedAt       string          `json:"created_at"`
	UpdatedAt       string          `json:"updated_at"`
}

func (q *Queries) GetProgram(ctx context.Context, id string) (GetProgramRow, error) {
	row := q.db.QueryRowContext(ctx, getProgram, id)
	var i GetProgramRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.CycleID,
		&i.WeeklyLookupID,
		&i.DailyLookupID,
		&i.DefaultRounding,
		&i.Difficulty,
		&i.DaysPerWeek,
		&i.Focus,
		&i.HasAmrap,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProgramBySlug = `-- name: GetProgramBySlug :one
SELECT id, name, slug, description, cycle_id, weekly_lookup_id, daily_lookup_id, default_rounding, difficulty, days_per_week, focus, has_amrap, created_at, updated_at
FROM programs
WHERE slug = ?
`

type GetProgramBySlugRow struct {
	ID              string          `json:"id"`
	Name            string          `json:"name"`
	Slug            string          `json:"slug"`
	Description     sql.NullString  `json:"description"`
	CycleID         string          `json:"cycle_id"`
	WeeklyLookupID  sql.NullString  `json:"weekly_lookup_id"`
	DailyLookupID   sql.NullString  `json:"daily_lookup_id"`
	DefaultRounding sql.NullFloat64 `json:"default_rounding"`
	Difficulty      string          `json:"difficulty"`
	DaysPerWeek     int64           `json:"days_per_week"`
	Focus           string          `json:"focus"`
	HasAmrap        int64           `json:"has_amrap"`
	CreatedAt       string          `json:"created_at"`
	UpdatedAt       string          `json:"updated_at"`
}

func (q *Queries) GetProgramBySlug(ctx context.Context, slug string) (GetProgramBySlugRow, error) {
	row := q.db.QueryRowContext(ctx, getProgramBySlug, slug)
	var i GetProgramBySlugRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.CycleID,
		&i.WeeklyLookupID,
		&i.DailyLookupID,
		&i.DefaultRounding,
		&i.Difficulty,
		&i.DaysPerWeek,
		&i.Focus,
		&i.HasAmrap,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProgramLiftRequirements = `-- name: GetProgramLiftRequirements :many
SELECT DISTINCT l.name
FROM lifts l
INNER JOIN prescriptions pr ON pr.lift_id = l.id
INNER JOIN day_prescriptions dp ON dp.prescription_id = pr.id
INNER JOIN days d ON d.id = dp.day_id
WHERE d.program_id = ?
ORDER BY l.name ASC
`

// Returns unique lift names used in a program, sorted alphabetically
func (q *Queries) GetProgramLiftRequirements(ctx context.Context, programID sql.NullString) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getProgramLiftRequirements, programID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var name string
		if err := rows.Scan(&name); err != nil {
			return nil, err
		}
		items = append(items, name)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProgramSampleWeek = `-- name: GetProgramSampleWeek :many
SELECT
    d.id,
    d.name,
    COALESCE(wd.day_of_week, 'MONDAY') as day_of_week,
    (SELECT COUNT(*) FROM day_prescriptions dp WHERE dp.day_id = d.id) as exercise_count
FROM days d
LEFT JOIN week_days wd ON wd.day_id = d.id
LEFT JOIN weeks w ON w.id = wd.week_id
LEFT JOIN cycles c ON c.id = w.cycle_id
LEFT JOIN programs p ON p.cycle_id = c.id
WHERE (p.id = ? OR d.program_id = ?)
  AND (w.week_number = 1 OR w.id IS NULL)
GROUP BY d.id
ORDER BY
    CASE wd.day_of_week
        WHEN 'MONDAY' THEN 1
        WHEN 'TUESDAY' THEN 2
        WHEN 'WEDNESDAY' THEN 3
        WHEN 'THURSDAY' THEN 4
        WHEN 'FRIDAY' THEN 5
        WHEN 'SATURDAY' THEN 6
        WHEN 'SUNDAY' THEN 7
        ELSE 8
    END,
    d.name ASC
`

type GetProgramSampleWeekParams struct {
	ID        string         `json:"id"`
	ProgramID sql.NullString `json:"program_id"`
}

type GetProgramSampleWeekRow struct {
	ID            string `json:"id"`
	Name          string `json:"name"`
	DayOfWeek     string `json:"day_of_week"`
	ExerciseCount int64  `json:"exercise_count"`
}

// Returns days for the first week of a program with prescription counts
// For programs with week_days, uses week 1; otherwise falls back to days.program_id
func (q *Queries) GetProgramSampleWeek(ctx context.Context, arg GetProgramSampleWeekParams) ([]GetProgramSampleWeekRow, error) {
	rows, err := q.db.QueryContext(ctx, getProgramSampleWeek, arg.ID, arg.ProgramID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetProgramSampleWeekRow{}
	for rows.Next() {
		var i GetProgramSampleWeekRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.DayOfWeek,
			&i.ExerciseCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProgramSessionStats = `-- name: GetProgramSessionStats :one
SELECT
    COALESCE(SUM(total_sets), 0) as total_sets,
    COALESCE(COUNT(DISTINCT d.id), 0) as total_days,
    COALESCE(SUM(exercise_count), 0) as total_exercises
FROM days d
LEFT JOIN (
    SELECT
        dp.day_id,
        COUNT(*) as exercise_count,
        SUM(
            CASE
                WHEN pr.set_scheme LIKE '%x%' THEN
                    CAST(SUBSTR(pr.set_scheme, 1, INSTR(pr.set_scheme, 'x') - 1) AS INTEGER)
                ELSE 3
            END
        ) as total_sets
    FROM day_prescriptions dp
    INNER JOIN prescriptions pr ON pr.id = dp.prescription_id
    GROUP BY dp.day_id
) stats ON stats.day_id = d.id
WHERE d.program_id = ?
`

type GetProgramSessionStatsRow struct {
	TotalSets      interface{} `json:"total_sets"`
	TotalDays      interface{} `json:"total_days"`
	TotalExercises interface{} `json:"total_exercises"`
}

// Returns total sets and exercises per average day for session duration estimation
func (q *Queries) GetProgramSessionStats(ctx context.Context, programID sql.NullString) (GetProgramSessionStatsRow, error) {
	row := q.db.QueryRowContext(ctx, getProgramSessionStats, programID)
	var i GetProgramSessionStatsRow
	err := row.Scan(&i.TotalSets, &i.TotalDays, &i.TotalExercises)
	return i, err
}

const getWeeklyLookupForProgram = `-- name: GetWeeklyLookupForProgram :one
SELECT id, name, entries, program_id, created_at, updated_at
FROM weekly_lookups
WHERE id = ?
`

func (q *Queries) GetWeeklyLookupForProgram(ctx context.Context, id string) (WeeklyLookup, error) {
	row := q.db.QueryRowContext(ctx, getWeeklyLookupForProgram, id)
	var i WeeklyLookup
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Entries,
		&i.ProgramID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listProgramsByCreatedAtAsc = `-- name: ListProgramsByCreatedAtAsc :many
SELECT id, name, slug, description, cycle_id, weekly_lookup_id, daily_lookup_id, default_rounding, difficulty, days_per_week, focus, has_amrap, created_at, updated_at
FROM programs
ORDER BY created_at ASC
LIMIT ? OFFSET ?
`

type ListProgramsByCreatedAtAscParams struct {
	Limit  int64 `json:"limit"`
	Offset int64 `json:"offset"`
}

type ListProgramsByCreatedAtAscRow struct {
	ID              string          `json:"id"`
	Name            string          `json:"name"`
	Slug            string          `json:"slug"`
	Description     sql.NullString  `json:"description"`
	CycleID         string          `json:"cycle_id"`
	WeeklyLookupID  sql.NullString  `json:"weekly_lookup_id"`
	DailyLookupID   sql.NullString  `json:"daily_lookup_id"`
	DefaultRounding sql.NullFloat64 `json:"default_rounding"`
	Difficulty      string          `json:"difficulty"`
	DaysPerWeek     int64           `json:"days_per_week"`
	Focus           string          `json:"focus"`
	HasAmrap        int64           `json:"has_amrap"`
	CreatedAt       string          `json:"created_at"`
	UpdatedAt       string          `json:"updated_at"`
}

func (q *Queries) ListProgramsByCreatedAtAsc(ctx context.Context, arg ListProgramsByCreatedAtAscParams) ([]ListProgramsByCreatedAtAscRow, error) {
	rows, err := q.db.QueryContext(ctx, listProgramsByCreatedAtAsc, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListProgramsByCreatedAtAscRow{}
	for rows.Next() {
		var i ListProgramsByCreatedAtAscRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Description,
			&i.CycleID,
			&i.WeeklyLookupID,
			&i.DailyLookupID,
			&i.DefaultRounding,
			&i.Difficulty,
			&i.DaysPerWeek,
			&i.Focus,
			&i.HasAmrap,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProgramsByCreatedAtDesc = `-- name: ListProgramsByCreatedAtDesc :many
SELECT id, name, slug, description, cycle_id, weekly_lookup_id, daily_lookup_id, default_rounding, difficulty, days_per_week, focus, has_amrap, created_at, updated_at
FROM programs
ORDER BY created_at DESC
LIMIT ? OFFSET ?
`

type ListProgramsByCreatedAtDescParams struct {
	Limit  int64 `json:"limit"`
	Offset int64 `json:"offset"`
}

type ListProgramsByCreatedAtDescRow struct {
	ID              string          `json:"id"`
	Name            string          `json:"name"`
	Slug            string          `json:"slug"`
	Description     sql.NullString  `json:"description"`
	CycleID         string          `json:"cycle_id"`
	WeeklyLookupID  sql.NullString  `json:"weekly_lookup_id"`
	DailyLookupID   sql.NullString  `json:"daily_lookup_id"`
	DefaultRounding sql.NullFloat64 `json:"default_rounding"`
	Difficulty      string          `json:"difficulty"`
	DaysPerWeek     int64           `json:"days_per_week"`
	Focus           string          `json:"focus"`
	HasAmrap        int64           `json:"has_amrap"`
	CreatedAt       string          `json:"created_at"`
	UpdatedAt       string          `json:"updated_at"`
}

func (q *Queries) ListProgramsByCreatedAtDesc(ctx context.Context, arg ListProgramsByCreatedAtDescParams) ([]ListProgramsByCreatedAtDescRow, error) {
	rows, err := q.db.QueryContext(ctx, listProgramsByCreatedAtDesc, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListProgramsByCreatedAtDescRow{}
	for rows.Next() {
		var i ListProgramsByCreatedAtDescRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Description,
			&i.CycleID,
			&i.WeeklyLookupID,
			&i.DailyLookupID,
			&i.DefaultRounding,
			&i.Difficulty,
			&i.DaysPerWeek,
			&i.Focus,
			&i.HasAmrap,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProgramsByNameAsc = `-- name: ListProgramsByNameAsc :many
SELECT id, name, slug, description, cycle_id, weekly_lookup_id, daily_lookup_id, default_rounding, difficulty, days_per_week, focus, has_amrap, created_at, updated_at
FROM programs
ORDER BY name ASC
LIMIT ? OFFSET ?
`

type ListProgramsByNameAscParams struct {
	Limit  int64 `json:"limit"`
	Offset int64 `json:"offset"`
}

type ListProgramsByNameAscRow struct {
	ID              string          `json:"id"`
	Name            string          `json:"name"`
	Slug            string          `json:"slug"`
	Description     sql.NullString  `json:"description"`
	CycleID         string          `json:"cycle_id"`
	WeeklyLookupID  sql.NullString  `json:"weekly_lookup_id"`
	DailyLookupID   sql.NullString  `json:"daily_lookup_id"`
	DefaultRounding sql.NullFloat64 `json:"default_rounding"`
	Difficulty      string          `json:"difficulty"`
	DaysPerWeek     int64           `json:"days_per_week"`
	Focus           string          `json:"focus"`
	HasAmrap        int64           `json:"has_amrap"`
	CreatedAt       string          `json:"created_at"`
	UpdatedAt       string          `json:"updated_at"`
}

func (q *Queries) ListProgramsByNameAsc(ctx context.Context, arg ListProgramsByNameAscParams) ([]ListProgramsByNameAscRow, error) {
	rows, err := q.db.QueryContext(ctx, listProgramsByNameAsc, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListProgramsByNameAscRow{}
	for rows.Next() {
		var i ListProgramsByNameAscRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Description,
			&i.CycleID,
			&i.WeeklyLookupID,
			&i.DailyLookupID,
			&i.DefaultRounding,
			&i.Difficulty,
			&i.DaysPerWeek,
			&i.Focus,
			&i.HasAmrap,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProgramsByNameDesc = `-- name: ListProgramsByNameDesc :many
SELECT id, name, slug, description, cycle_id, weekly_lookup_id, daily_lookup_id, default_rounding, difficulty, days_per_week, focus, has_amrap, created_at, updated_at
FROM programs
ORDER BY name DESC
LIMIT ? OFFSET ?
`

type ListProgramsByNameDescParams struct {
	Limit  int64 `json:"limit"`
	Offset int64 `json:"offset"`
}

type ListProgramsByNameDescRow struct {
	ID              string          `json:"id"`
	Name            string          `json:"name"`
	Slug            string          `json:"slug"`
	Description     sql.NullString  `json:"description"`
	CycleID         string          `json:"cycle_id"`
	WeeklyLookupID  sql.NullString  `json:"weekly_lookup_id"`
	DailyLookupID   sql.NullString  `json:"daily_lookup_id"`
	DefaultRounding sql.NullFloat64 `json:"default_rounding"`
	Difficulty      string          `json:"difficulty"`
	DaysPerWeek     int64           `json:"days_per_week"`
	Focus           string          `json:"focus"`
	HasAmrap        int64           `json:"has_amrap"`
	CreatedAt       string          `json:"created_at"`
	UpdatedAt       string          `json:"updated_at"`
}

func (q *Queries) ListProgramsByNameDesc(ctx context.Context, arg ListProgramsByNameDescParams) ([]ListProgramsByNameDescRow, error) {
	rows, err := q.db.QueryContext(ctx, listProgramsByNameDesc, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListProgramsByNameDescRow{}
	for rows.Next() {
		var i ListProgramsByNameDescRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Description,
			&i.CycleID,
			&i.WeeklyLookupID,
			&i.DailyLookupID,
			&i.DefaultRounding,
			&i.Difficulty,
			&i.DaysPerWeek,
			&i.Focus,
			&i.HasAmrap,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProgramsFilteredByCreatedAtAsc = `-- name: ListProgramsFilteredByCreatedAtAsc :many
SELECT id, name, slug, description, cycle_id, weekly_lookup_id, daily_lookup_id, default_rounding, difficulty, days_per_week, focus, has_amrap, created_at, updated_at
FROM programs
WHERE (?1 IS NULL OR difficulty = ?1)
  AND (?2 IS NULL OR days_per_week = ?2)
  AND (?3 IS NULL OR focus = ?3)
  AND (?4 IS NULL OR has_amrap = ?4)
  AND (?5 IS NULL OR name LIKE '%' || ?5 || '%' COLLATE NOCASE)
ORDER BY created_at ASC
LIMIT ?7 OFFSET ?6
`

type ListProgramsFilteredByCreatedAtAscParams struct {
	Difficulty  interface{} `json:"difficulty"`
	DaysPerWeek interface{} `json:"days_per_week"`
	Focus       interface{} `json:"focus"`
	HasAmrap    interface{} `json:"has_amrap"`
	Search      interface{} `json:"search"`
	Offset      int64       `json:"offset"`
	Limit       int64       `json:"limit"`
}

type ListProgramsFilteredByCreatedAtAscRow struct {
	ID              string          `json:"id"`
	Name            string          `json:"name"`
	Slug            string          `json:"slug"`
	Description     sql.NullString  `json:"description"`
	CycleID         string          `json:"cycle_id"`
	WeeklyLookupID  sql.NullString  `json:"weekly_lookup_id"`
	DailyLookupID   sql.NullString  `json:"daily_lookup_id"`
	DefaultRounding sql.NullFloat64 `json:"default_rounding"`
	Difficulty      string          `json:"difficulty"`
	DaysPerWeek     int64           `json:"days_per_week"`
	Focus           string          `json:"focus"`
	HasAmrap        int64           `json:"has_amrap"`
	CreatedAt       string          `json:"created_at"`
	UpdatedAt       string          `json:"updated_at"`
}

func (q *Queries) ListProgramsFilteredByCreatedAtAsc(ctx context.Context, arg ListProgramsFilteredByCreatedAtAscParams) ([]ListProgramsFilteredByCreatedAtAscRow, error) {
	rows, err := q.db.QueryContext(ctx, listProgramsFilteredByCreatedAtAsc,
		arg.Difficulty,
		arg.DaysPerWeek,
		arg.Focus,
		arg.HasAmrap,
		arg.Search,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListProgramsFilteredByCreatedAtAscRow{}
	for rows.Next() {
		var i ListProgramsFilteredByCreatedAtAscRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Description,
			&i.CycleID,
			&i.WeeklyLookupID,
			&i.DailyLookupID,
			&i.DefaultRounding,
			&i.Difficulty,
			&i.DaysPerWeek,
			&i.Focus,
			&i.HasAmrap,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProgramsFilteredByCreatedAtDesc = `-- name: ListProgramsFilteredByCreatedAtDesc :many
SELECT id, name, slug, description, cycle_id, weekly_lookup_id, daily_lookup_id, default_rounding, difficulty, days_per_week, focus, has_amrap, created_at, updated_at
FROM programs
WHERE (?1 IS NULL OR difficulty = ?1)
  AND (?2 IS NULL OR days_per_week = ?2)
  AND (?3 IS NULL OR focus = ?3)
  AND (?4 IS NULL OR has_amrap = ?4)
  AND (?5 IS NULL OR name LIKE '%' || ?5 || '%' COLLATE NOCASE)
ORDER BY created_at DESC
LIMIT ?7 OFFSET ?6
`

type ListProgramsFilteredByCreatedAtDescParams struct {
	Difficulty  interface{} `json:"difficulty"`
	DaysPerWeek interface{} `json:"days_per_week"`
	Focus       interface{} `json:"focus"`
	HasAmrap    interface{} `json:"has_amrap"`
	Search      interface{} `json:"search"`
	Offset      int64       `json:"offset"`
	Limit       int64       `json:"limit"`
}

type ListProgramsFilteredByCreatedAtDescRow struct {
	ID              string          `json:"id"`
	Name            string          `json:"name"`
	Slug            string          `json:"slug"`
	Description     sql.NullString  `json:"description"`
	CycleID         string          `json:"cycle_id"`
	WeeklyLookupID  sql.NullString  `json:"weekly_lookup_id"`
	DailyLookupID   sql.NullString  `json:"daily_lookup_id"`
	DefaultRounding sql.NullFloat64 `json:"default_rounding"`
	Difficulty      string          `json:"difficulty"`
	DaysPerWeek     int64           `json:"days_per_week"`
	Focus           string          `json:"focus"`
	HasAmrap        int64           `json:"has_amrap"`
	CreatedAt       string          `json:"created_at"`
	UpdatedAt       string          `json:"updated_at"`
}

func (q *Queries) ListProgramsFilteredByCreatedAtDesc(ctx context.Context, arg ListProgramsFilteredByCreatedAtDescParams) ([]ListProgramsFilteredByCreatedAtDescRow, error) {
	rows, err := q.db.QueryContext(ctx, listProgramsFilteredByCreatedAtDesc,
		arg.Difficulty,
		arg.DaysPerWeek,
		arg.Focus,
		arg.HasAmrap,
		arg.Search,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListProgramsFilteredByCreatedAtDescRow{}
	for rows.Next() {
		var i ListProgramsFilteredByCreatedAtDescRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Description,
			&i.CycleID,
			&i.WeeklyLookupID,
			&i.DailyLookupID,
			&i.DefaultRounding,
			&i.Difficulty,
			&i.DaysPerWeek,
			&i.Focus,
			&i.HasAmrap,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProgramsFilteredByNameAsc = `-- name: ListProgramsFilteredByNameAsc :many
SELECT id, name, slug, description, cycle_id, weekly_lookup_id, daily_lookup_id, default_rounding, difficulty, days_per_week, focus, has_amrap, created_at, updated_at
FROM programs
WHERE (?1 IS NULL OR difficulty = ?1)
  AND (?2 IS NULL OR days_per_week = ?2)
  AND (?3 IS NULL OR focus = ?3)
  AND (?4 IS NULL OR has_amrap = ?4)
  AND (?5 IS NULL OR name LIKE '%' || ?5 || '%' COLLATE NOCASE)
ORDER BY name ASC
LIMIT ?7 OFFSET ?6
`

type ListProgramsFilteredByNameAscParams struct {
	Difficulty  interface{} `json:"difficulty"`
	DaysPerWeek interface{} `json:"days_per_week"`
	Focus       interface{} `json:"focus"`
	HasAmrap    interface{} `json:"has_amrap"`
	Search      interface{} `json:"search"`
	Offset      int64       `json:"offset"`
	Limit       int64       `json:"limit"`
}

type ListProgramsFilteredByNameAscRow struct {
	ID              string          `json:"id"`
	Name            string          `json:"name"`
	Slug            string          `json:"slug"`
	Description     sql.NullString  `json:"description"`
	CycleID         string          `json:"cycle_id"`
	WeeklyLookupID  sql.NullString  `json:"weekly_lookup_id"`
	DailyLookupID   sql.NullString  `json:"daily_lookup_id"`
	DefaultRounding sql.NullFloat64 `json:"default_rounding"`
	Difficulty      string          `json:"difficulty"`
	DaysPerWeek     int64           `json:"days_per_week"`
	Focus           string          `json:"focus"`
	HasAmrap        int64           `json:"has_amrap"`
	CreatedAt       string          `json:"created_at"`
	UpdatedAt       string          `json:"updated_at"`
}

func (q *Queries) ListProgramsFilteredByNameAsc(ctx context.Context, arg ListProgramsFilteredByNameAscParams) ([]ListProgramsFilteredByNameAscRow, error) {
	rows, err := q.db.QueryContext(ctx, listProgramsFilteredByNameAsc,
		arg.Difficulty,
		arg.DaysPerWeek,
		arg.Focus,
		arg.HasAmrap,
		arg.Search,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListProgramsFilteredByNameAscRow{}
	for rows.Next() {
		var i ListProgramsFilteredByNameAscRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Description,
			&i.CycleID,
			&i.WeeklyLookupID,
			&i.DailyLookupID,
			&i.DefaultRounding,
			&i.Difficulty,
			&i.DaysPerWeek,
			&i.Focus,
			&i.HasAmrap,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProgramsFilteredByNameDesc = `-- name: ListProgramsFilteredByNameDesc :many
SELECT id, name, slug, description, cycle_id, weekly_lookup_id, daily_lookup_id, default_rounding, difficulty, days_per_week, focus, has_amrap, created_at, updated_at
FROM programs
WHERE (?1 IS NULL OR difficulty = ?1)
  AND (?2 IS NULL OR days_per_week = ?2)
  AND (?3 IS NULL OR focus = ?3)
  AND (?4 IS NULL OR has_amrap = ?4)
  AND (?5 IS NULL OR name LIKE '%' || ?5 || '%' COLLATE NOCASE)
ORDER BY name DESC
LIMIT ?7 OFFSET ?6
`

type ListProgramsFilteredByNameDescParams struct {
	Difficulty  interface{} `json:"difficulty"`
	DaysPerWeek interface{} `json:"days_per_week"`
	Focus       interface{} `json:"focus"`
	HasAmrap    interface{} `json:"has_amrap"`
	Search      interface{} `json:"search"`
	Offset      int64       `json:"offset"`
	Limit       int64       `json:"limit"`
}

type ListProgramsFilteredByNameDescRow struct {
	ID              string          `json:"id"`
	Name            string          `json:"name"`
	Slug            string          `json:"slug"`
	Description     sql.NullString  `json:"description"`
	CycleID         string          `json:"cycle_id"`
	WeeklyLookupID  sql.NullString  `json:"weekly_lookup_id"`
	DailyLookupID   sql.NullString  `json:"daily_lookup_id"`
	DefaultRounding sql.NullFloat64 `json:"default_rounding"`
	Difficulty      string          `json:"difficulty"`
	DaysPerWeek     int64           `json:"days_per_week"`
	Focus           string          `json:"focus"`
	HasAmrap        int64           `json:"has_amrap"`
	CreatedAt       string          `json:"created_at"`
	UpdatedAt       string          `json:"updated_at"`
}

func (q *Queries) ListProgramsFilteredByNameDesc(ctx context.Context, arg ListProgramsFilteredByNameDescParams) ([]ListProgramsFilteredByNameDescRow, error) {
	rows, err := q.db.QueryContext(ctx, listProgramsFilteredByNameDesc,
		arg.Difficulty,
		arg.DaysPerWeek,
		arg.Focus,
		arg.HasAmrap,
		arg.Search,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListProgramsFilteredByNameDescRow{}
	for rows.Next() {
		var i ListProgramsFilteredByNameDescRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Description,
			&i.CycleID,
			&i.WeeklyLookupID,
			&i.DailyLookupID,
			&i.DefaultRounding,
			&i.Difficulty,
			&i.DaysPerWeek,
			&i.Focus,
			&i.HasAmrap,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const programHasEnrolledUsers = `-- name: ProgramHasEnrolledUsers :one
SELECT EXISTS(
    SELECT 1 FROM user_program_states ups
    WHERE ups.program_id = ?
) AS has_enrolled
`

func (q *Queries) ProgramHasEnrolledUsers(ctx context.Context, programID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, programHasEnrolledUsers, programID)
	var has_enrolled int64
	err := row.Scan(&has_enrolled)
	return has_enrolled, err
}

const programSlugExists = `-- name: ProgramSlugExists :one
SELECT EXISTS(
    SELECT 1 FROM programs WHERE slug = ?
) AS slug_exists
`

func (q *Queries) ProgramSlugExists(ctx context.Context, slug string) (int64, error) {
	row := q.db.QueryRowContext(ctx, programSlugExists, slug)
	var slug_exists int64
	err := row.Scan(&slug_exists)
	return slug_exists, err
}

const programSlugExistsExcluding = `-- name: ProgramSlugExistsExcluding :one
SELECT EXISTS(
    SELECT 1 FROM programs WHERE slug = ? AND id != ?
) AS slug_exists
`

type ProgramSlugExistsExcludingParams struct {
	Slug string `json:"slug"`
	ID   string `json:"id"`
}

func (q *Queries) ProgramSlugExistsExcluding(ctx context.Context, arg ProgramSlugExistsExcludingParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, programSlugExistsExcluding, arg.Slug, arg.ID)
	var slug_exists int64
	err := row.Scan(&slug_exists)
	return slug_exists, err
}

const updateProgram = `-- name: UpdateProgram :exec
UPDATE programs
SET name = ?, slug = ?, description = ?, cycle_id = ?, weekly_lookup_id = ?, daily_lookup_id = ?, default_rounding = ?, difficulty = ?, days_per_week = ?, focus = ?, has_amrap = ?, updated_at = ?
WHERE id = ?
`

type UpdateProgramParams struct {
	Name            string          `json:"name"`
	Slug            string          `json:"slug"`
	Description     sql.NullString  `json:"description"`
	CycleID         string          `json:"cycle_id"`
	WeeklyLookupID  sql.NullString  `json:"weekly_lookup_id"`
	DailyLookupID   sql.NullString  `json:"daily_lookup_id"`
	DefaultRounding sql.NullFloat64 `json:"default_rounding"`
	Difficulty      string          `json:"difficulty"`
	DaysPerWeek     int64           `json:"days_per_week"`
	Focus           string          `json:"focus"`
	HasAmrap        int64           `json:"has_amrap"`
	UpdatedAt       string          `json:"updated_at"`
	ID              string          `json:"id"`
}

func (q *Queries) UpdateProgram(ctx context.Context, arg UpdateProgramParams) error {
	_, err := q.db.ExecContext(ctx, updateProgram,
		arg.Name,
		arg.Slug,
		arg.Description,
		arg.CycleID,
		arg.WeeklyLookupID,
		arg.DailyLookupID,
		arg.DefaultRounding,
		arg.Difficulty,
		arg.DaysPerWeek,
		arg.Focus,
		arg.HasAmrap,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}
