// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: progressions.sql

package db

import (
	"context"
)

const countProgressions = `-- name: CountProgressions :one
SELECT COUNT(*) FROM progressions
`

func (q *Queries) CountProgressions(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countProgressions)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countProgressionsByType = `-- name: CountProgressionsByType :one
SELECT COUNT(*) FROM progressions WHERE type = ?
`

func (q *Queries) CountProgressionsByType(ctx context.Context, type_ string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countProgressionsByType, type_)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createProgression = `-- name: CreateProgression :exec
INSERT INTO progressions (id, name, type, parameters, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?)
`

type CreateProgressionParams struct {
	ID         string `json:"id"`
	Name       string `json:"name"`
	Type       string `json:"type"`
	Parameters string `json:"parameters"`
	CreatedAt  string `json:"created_at"`
	UpdatedAt  string `json:"updated_at"`
}

func (q *Queries) CreateProgression(ctx context.Context, arg CreateProgressionParams) error {
	_, err := q.db.ExecContext(ctx, createProgression,
		arg.ID,
		arg.Name,
		arg.Type,
		arg.Parameters,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const deleteProgression = `-- name: DeleteProgression :exec
DELETE FROM progressions WHERE id = ?
`

func (q *Queries) DeleteProgression(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteProgression, id)
	return err
}

const getProgression = `-- name: GetProgression :one
SELECT id, name, type, parameters, created_at, updated_at
FROM progressions
WHERE id = ?
`

func (q *Queries) GetProgression(ctx context.Context, id string) (Progression, error) {
	row := q.db.QueryRowContext(ctx, getProgression, id)
	var i Progression
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.Parameters,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listProgressions = `-- name: ListProgressions :many
SELECT id, name, type, parameters, created_at, updated_at
FROM progressions
ORDER BY name ASC
LIMIT ? OFFSET ?
`

type ListProgressionsParams struct {
	Limit  int64 `json:"limit"`
	Offset int64 `json:"offset"`
}

func (q *Queries) ListProgressions(ctx context.Context, arg ListProgressionsParams) ([]Progression, error) {
	rows, err := q.db.QueryContext(ctx, listProgressions, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Progression{}
	for rows.Next() {
		var i Progression
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Type,
			&i.Parameters,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProgressionsByType = `-- name: ListProgressionsByType :many
SELECT id, name, type, parameters, created_at, updated_at
FROM progressions
WHERE type = ?
ORDER BY name ASC
LIMIT ? OFFSET ?
`

type ListProgressionsByTypeParams struct {
	Type   string `json:"type"`
	Limit  int64  `json:"limit"`
	Offset int64  `json:"offset"`
}

func (q *Queries) ListProgressionsByType(ctx context.Context, arg ListProgressionsByTypeParams) ([]Progression, error) {
	rows, err := q.db.QueryContext(ctx, listProgressionsByType, arg.Type, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Progression{}
	for rows.Next() {
		var i Progression
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Type,
			&i.Parameters,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProgression = `-- name: UpdateProgression :exec
UPDATE progressions
SET name = ?, type = ?, parameters = ?, updated_at = ?
WHERE id = ?
`

type UpdateProgressionParams struct {
	Name       string `json:"name"`
	Type       string `json:"type"`
	Parameters string `json:"parameters"`
	UpdatedAt  string `json:"updated_at"`
	ID         string `json:"id"`
}

func (q *Queries) UpdateProgression(ctx context.Context, arg UpdateProgressionParams) error {
	_, err := q.db.ExecContext(ctx, updateProgression,
		arg.Name,
		arg.Type,
		arg.Parameters,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}
