// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: program_progressions.sql

package db

import (
	"context"
	"database/sql"
)

const countProgramProgressionsByProgram = `-- name: CountProgramProgressionsByProgram :one
SELECT COUNT(*) FROM program_progressions WHERE program_id = ?
`

func (q *Queries) CountProgramProgressionsByProgram(ctx context.Context, programID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countProgramProgressionsByProgram, programID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countProgramProgressionsByProgression = `-- name: CountProgramProgressionsByProgression :one
SELECT COUNT(*) FROM program_progressions WHERE progression_id = ?
`

func (q *Queries) CountProgramProgressionsByProgression(ctx context.Context, progressionID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countProgramProgressionsByProgression, progressionID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createProgramProgression = `-- name: CreateProgramProgression :exec
INSERT INTO program_progressions (id, program_id, progression_id, lift_id, priority, enabled, override_increment, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateProgramProgressionParams struct {
	ID                string          `json:"id"`
	ProgramID         string          `json:"program_id"`
	ProgressionID     string          `json:"progression_id"`
	LiftID            sql.NullString  `json:"lift_id"`
	Priority          int64           `json:"priority"`
	Enabled           int64           `json:"enabled"`
	OverrideIncrement sql.NullFloat64 `json:"override_increment"`
	CreatedAt         string          `json:"created_at"`
	UpdatedAt         string          `json:"updated_at"`
}

func (q *Queries) CreateProgramProgression(ctx context.Context, arg CreateProgramProgressionParams) error {
	_, err := q.db.ExecContext(ctx, createProgramProgression,
		arg.ID,
		arg.ProgramID,
		arg.ProgressionID,
		arg.LiftID,
		arg.Priority,
		arg.Enabled,
		arg.OverrideIncrement,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const deleteProgramProgression = `-- name: DeleteProgramProgression :exec
DELETE FROM program_progressions WHERE id = ?
`

func (q *Queries) DeleteProgramProgression(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteProgramProgression, id)
	return err
}

const deleteProgramProgressionsByProgram = `-- name: DeleteProgramProgressionsByProgram :exec
DELETE FROM program_progressions WHERE program_id = ?
`

func (q *Queries) DeleteProgramProgressionsByProgram(ctx context.Context, programID string) error {
	_, err := q.db.ExecContext(ctx, deleteProgramProgressionsByProgram, programID)
	return err
}

const getProgramProgression = `-- name: GetProgramProgression :one
SELECT id, program_id, progression_id, lift_id, priority, enabled, override_increment, created_at, updated_at
FROM program_progressions
WHERE id = ?
`

func (q *Queries) GetProgramProgression(ctx context.Context, id string) (ProgramProgression, error) {
	row := q.db.QueryRowContext(ctx, getProgramProgression, id)
	var i ProgramProgression
	err := row.Scan(
		&i.ID,
		&i.ProgramID,
		&i.ProgressionID,
		&i.LiftID,
		&i.Priority,
		&i.Enabled,
		&i.OverrideIncrement,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listEnabledProgramProgressionsByProgram = `-- name: ListEnabledProgramProgressionsByProgram :many
SELECT id, program_id, progression_id, lift_id, priority, enabled, override_increment, created_at, updated_at
FROM program_progressions
WHERE program_id = ? AND enabled = 1
ORDER BY priority ASC
`

func (q *Queries) ListEnabledProgramProgressionsByProgram(ctx context.Context, programID string) ([]ProgramProgression, error) {
	rows, err := q.db.QueryContext(ctx, listEnabledProgramProgressionsByProgram, programID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProgramProgression{}
	for rows.Next() {
		var i ProgramProgression
		if err := rows.Scan(
			&i.ID,
			&i.ProgramID,
			&i.ProgressionID,
			&i.LiftID,
			&i.Priority,
			&i.Enabled,
			&i.OverrideIncrement,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProgramProgressionsByProgram = `-- name: ListProgramProgressionsByProgram :many
SELECT id, program_id, progression_id, lift_id, priority, enabled, override_increment, created_at, updated_at
FROM program_progressions
WHERE program_id = ?
ORDER BY priority ASC
`

func (q *Queries) ListProgramProgressionsByProgram(ctx context.Context, programID string) ([]ProgramProgression, error) {
	rows, err := q.db.QueryContext(ctx, listProgramProgressionsByProgram, programID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProgramProgression{}
	for rows.Next() {
		var i ProgramProgression
		if err := rows.Scan(
			&i.ID,
			&i.ProgramID,
			&i.ProgressionID,
			&i.LiftID,
			&i.Priority,
			&i.Enabled,
			&i.OverrideIncrement,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProgramProgressionsByProgramAndLift = `-- name: ListProgramProgressionsByProgramAndLift :many
SELECT id, program_id, progression_id, lift_id, priority, enabled, override_increment, created_at, updated_at
FROM program_progressions
WHERE program_id = ? AND (lift_id = ? OR lift_id IS NULL) AND enabled = 1
ORDER BY priority ASC
`

type ListProgramProgressionsByProgramAndLiftParams struct {
	ProgramID string         `json:"program_id"`
	LiftID    sql.NullString `json:"lift_id"`
}

func (q *Queries) ListProgramProgressionsByProgramAndLift(ctx context.Context, arg ListProgramProgressionsByProgramAndLiftParams) ([]ProgramProgression, error) {
	rows, err := q.db.QueryContext(ctx, listProgramProgressionsByProgramAndLift, arg.ProgramID, arg.LiftID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProgramProgression{}
	for rows.Next() {
		var i ProgramProgression
		if err := rows.Scan(
			&i.ID,
			&i.ProgramID,
			&i.ProgressionID,
			&i.LiftID,
			&i.Priority,
			&i.Enabled,
			&i.OverrideIncrement,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProgramProgression = `-- name: UpdateProgramProgression :exec
UPDATE program_progressions
SET priority = ?, enabled = ?, override_increment = ?, updated_at = ?
WHERE id = ?
`

type UpdateProgramProgressionParams struct {
	Priority          int64           `json:"priority"`
	Enabled           int64           `json:"enabled"`
	OverrideIncrement sql.NullFloat64 `json:"override_increment"`
	UpdatedAt         string          `json:"updated_at"`
	ID                string          `json:"id"`
}

func (q *Queries) UpdateProgramProgression(ctx context.Context, arg UpdateProgramProgressionParams) error {
	_, err := q.db.ExecContext(ctx, updateProgramProgression,
		arg.Priority,
		arg.Enabled,
		arg.OverrideIncrement,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}
