// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: progression_logs.sql

package db

import (
	"context"
	"database/sql"
)

const checkIdempotency = `-- name: CheckIdempotency :one
SELECT EXISTS(
    SELECT 1 FROM progression_logs
    WHERE user_id = ? AND progression_id = ? AND lift_id = ? AND trigger_type = ? AND applied_at = ?
) AS already_applied
`

type CheckIdempotencyParams struct {
	UserID        string `json:"user_id"`
	ProgressionID string `json:"progression_id"`
	LiftID        string `json:"lift_id"`
	TriggerType   string `json:"trigger_type"`
	AppliedAt     string `json:"applied_at"`
}

func (q *Queries) CheckIdempotency(ctx context.Context, arg CheckIdempotencyParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, checkIdempotency,
		arg.UserID,
		arg.ProgressionID,
		arg.LiftID,
		arg.TriggerType,
		arg.AppliedAt,
	)
	var already_applied int64
	err := row.Scan(&already_applied)
	return already_applied, err
}

const countProgressionHistoryBase = `-- name: CountProgressionHistoryBase :one
SELECT COUNT(*) FROM progression_logs pl
WHERE pl.user_id = ?
`

func (q *Queries) CountProgressionHistoryBase(ctx context.Context, userID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countProgressionHistoryBase, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countProgressionLogsByUser = `-- name: CountProgressionLogsByUser :one
SELECT COUNT(*) FROM progression_logs WHERE user_id = ?
`

func (q *Queries) CountProgressionLogsByUser(ctx context.Context, userID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countProgressionLogsByUser, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countProgressionLogsByUserAndLift = `-- name: CountProgressionLogsByUserAndLift :one
SELECT COUNT(*) FROM progression_logs WHERE user_id = ? AND lift_id = ?
`

type CountProgressionLogsByUserAndLiftParams struct {
	UserID string `json:"user_id"`
	LiftID string `json:"lift_id"`
}

func (q *Queries) CountProgressionLogsByUserAndLift(ctx context.Context, arg CountProgressionLogsByUserAndLiftParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countProgressionLogsByUserAndLift, arg.UserID, arg.LiftID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createProgressionLog = `-- name: CreateProgressionLog :exec
INSERT INTO progression_logs (id, user_id, progression_id, lift_id, previous_value, new_value, delta, trigger_type, trigger_context, applied_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateProgressionLogParams struct {
	ID             string         `json:"id"`
	UserID         string         `json:"user_id"`
	ProgressionID  string         `json:"progression_id"`
	LiftID         string         `json:"lift_id"`
	PreviousValue  float64        `json:"previous_value"`
	NewValue       float64        `json:"new_value"`
	Delta          float64        `json:"delta"`
	TriggerType    string         `json:"trigger_type"`
	TriggerContext sql.NullString `json:"trigger_context"`
	AppliedAt      string         `json:"applied_at"`
}

func (q *Queries) CreateProgressionLog(ctx context.Context, arg CreateProgressionLogParams) error {
	_, err := q.db.ExecContext(ctx, createProgressionLog,
		arg.ID,
		arg.UserID,
		arg.ProgressionID,
		arg.LiftID,
		arg.PreviousValue,
		arg.NewValue,
		arg.Delta,
		arg.TriggerType,
		arg.TriggerContext,
		arg.AppliedAt,
	)
	return err
}

const deleteProgressionLog = `-- name: DeleteProgressionLog :exec
DELETE FROM progression_logs WHERE id = ?
`

func (q *Queries) DeleteProgressionLog(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteProgressionLog, id)
	return err
}

const getProgressionLog = `-- name: GetProgressionLog :one
SELECT id, user_id, progression_id, lift_id, previous_value, new_value, delta, trigger_type, trigger_context, applied_at
FROM progression_logs
WHERE id = ?
`

func (q *Queries) GetProgressionLog(ctx context.Context, id string) (ProgressionLog, error) {
	row := q.db.QueryRowContext(ctx, getProgressionLog, id)
	var i ProgressionLog
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ProgressionID,
		&i.LiftID,
		&i.PreviousValue,
		&i.NewValue,
		&i.Delta,
		&i.TriggerType,
		&i.TriggerContext,
		&i.AppliedAt,
	)
	return i, err
}

const listProgressionHistoryBase = `-- name: ListProgressionHistoryBase :many
SELECT
    pl.id,
    pl.user_id,
    pl.progression_id,
    pl.lift_id,
    pl.previous_value,
    pl.new_value,
    pl.delta,
    pl.trigger_type,
    pl.trigger_context,
    pl.applied_at,
    p.name AS progression_name,
    p.type AS progression_type,
    l.name AS lift_name
FROM progression_logs pl
JOIN progressions p ON pl.progression_id = p.id
JOIN lifts l ON pl.lift_id = l.id
WHERE pl.user_id = ?
ORDER BY pl.applied_at DESC
LIMIT ? OFFSET ?
`

type ListProgressionHistoryBaseParams struct {
	UserID string `json:"user_id"`
	Limit  int64  `json:"limit"`
	Offset int64  `json:"offset"`
}

type ListProgressionHistoryBaseRow struct {
	ID              string         `json:"id"`
	UserID          string         `json:"user_id"`
	ProgressionID   string         `json:"progression_id"`
	LiftID          string         `json:"lift_id"`
	PreviousValue   float64        `json:"previous_value"`
	NewValue        float64        `json:"new_value"`
	Delta           float64        `json:"delta"`
	TriggerType     string         `json:"trigger_type"`
	TriggerContext  sql.NullString `json:"trigger_context"`
	AppliedAt       string         `json:"applied_at"`
	ProgressionName string         `json:"progression_name"`
	ProgressionType string         `json:"progression_type"`
	LiftName        string         `json:"lift_name"`
}

func (q *Queries) ListProgressionHistoryBase(ctx context.Context, arg ListProgressionHistoryBaseParams) ([]ListProgressionHistoryBaseRow, error) {
	rows, err := q.db.QueryContext(ctx, listProgressionHistoryBase, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListProgressionHistoryBaseRow{}
	for rows.Next() {
		var i ListProgressionHistoryBaseRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ProgressionID,
			&i.LiftID,
			&i.PreviousValue,
			&i.NewValue,
			&i.Delta,
			&i.TriggerType,
			&i.TriggerContext,
			&i.AppliedAt,
			&i.ProgressionName,
			&i.ProgressionType,
			&i.LiftName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProgressionLogsByUser = `-- name: ListProgressionLogsByUser :many
SELECT id, user_id, progression_id, lift_id, previous_value, new_value, delta, trigger_type, trigger_context, applied_at
FROM progression_logs
WHERE user_id = ?
ORDER BY applied_at DESC
LIMIT ? OFFSET ?
`

type ListProgressionLogsByUserParams struct {
	UserID string `json:"user_id"`
	Limit  int64  `json:"limit"`
	Offset int64  `json:"offset"`
}

func (q *Queries) ListProgressionLogsByUser(ctx context.Context, arg ListProgressionLogsByUserParams) ([]ProgressionLog, error) {
	rows, err := q.db.QueryContext(ctx, listProgressionLogsByUser, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProgressionLog{}
	for rows.Next() {
		var i ProgressionLog
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ProgressionID,
			&i.LiftID,
			&i.PreviousValue,
			&i.NewValue,
			&i.Delta,
			&i.TriggerType,
			&i.TriggerContext,
			&i.AppliedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProgressionLogsByUserAndLift = `-- name: ListProgressionLogsByUserAndLift :many
SELECT id, user_id, progression_id, lift_id, previous_value, new_value, delta, trigger_type, trigger_context, applied_at
FROM progression_logs
WHERE user_id = ? AND lift_id = ?
ORDER BY applied_at DESC
LIMIT ? OFFSET ?
`

type ListProgressionLogsByUserAndLiftParams struct {
	UserID string `json:"user_id"`
	LiftID string `json:"lift_id"`
	Limit  int64  `json:"limit"`
	Offset int64  `json:"offset"`
}

func (q *Queries) ListProgressionLogsByUserAndLift(ctx context.Context, arg ListProgressionLogsByUserAndLiftParams) ([]ProgressionLog, error) {
	rows, err := q.db.QueryContext(ctx, listProgressionLogsByUserAndLift,
		arg.UserID,
		arg.LiftID,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProgressionLog{}
	for rows.Next() {
		var i ProgressionLog
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ProgressionID,
			&i.LiftID,
			&i.PreviousValue,
			&i.NewValue,
			&i.Delta,
			&i.TriggerType,
			&i.TriggerContext,
			&i.AppliedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
