// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: programs.sql

package db

import (
	"context"
	"database/sql"
)

const countEnrolledUsers = `-- name: CountEnrolledUsers :one
SELECT COUNT(*) FROM user_program_states WHERE program_id = ?
`

func (q *Queries) CountEnrolledUsers(ctx context.Context, programID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countEnrolledUsers, programID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countPrograms = `-- name: CountPrograms :one
SELECT COUNT(*) FROM programs
`

func (q *Queries) CountPrograms(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countPrograms)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createProgram = `-- name: CreateProgram :exec
INSERT INTO programs (id, name, slug, description, cycle_id, weekly_lookup_id, daily_lookup_id, default_rounding, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateProgramParams struct {
	ID              string          `json:"id"`
	Name            string          `json:"name"`
	Slug            string          `json:"slug"`
	Description     sql.NullString  `json:"description"`
	CycleID         string          `json:"cycle_id"`
	WeeklyLookupID  sql.NullString  `json:"weekly_lookup_id"`
	DailyLookupID   sql.NullString  `json:"daily_lookup_id"`
	DefaultRounding sql.NullFloat64 `json:"default_rounding"`
	CreatedAt       string          `json:"created_at"`
	UpdatedAt       string          `json:"updated_at"`
}

func (q *Queries) CreateProgram(ctx context.Context, arg CreateProgramParams) error {
	_, err := q.db.ExecContext(ctx, createProgram,
		arg.ID,
		arg.Name,
		arg.Slug,
		arg.Description,
		arg.CycleID,
		arg.WeeklyLookupID,
		arg.DailyLookupID,
		arg.DefaultRounding,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const deleteProgram = `-- name: DeleteProgram :exec
DELETE FROM programs WHERE id = ?
`

func (q *Queries) DeleteProgram(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteProgram, id)
	return err
}

const getCycleForProgram = `-- name: GetCycleForProgram :one
SELECT c.id, c.name, c.length_weeks, c.created_at, c.updated_at
FROM cycles c
WHERE c.id = ?
`

func (q *Queries) GetCycleForProgram(ctx context.Context, id string) (Cycle, error) {
	row := q.db.QueryRowContext(ctx, getCycleForProgram, id)
	var i Cycle
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.LengthWeeks,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDailyLookupForProgram = `-- name: GetDailyLookupForProgram :one
SELECT id, name, entries, program_id, created_at, updated_at
FROM daily_lookups
WHERE id = ?
`

func (q *Queries) GetDailyLookupForProgram(ctx context.Context, id string) (DailyLookup, error) {
	row := q.db.QueryRowContext(ctx, getDailyLookupForProgram, id)
	var i DailyLookup
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Entries,
		&i.ProgramID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProgram = `-- name: GetProgram :one
SELECT id, name, slug, description, cycle_id, weekly_lookup_id, daily_lookup_id, default_rounding, created_at, updated_at
FROM programs
WHERE id = ?
`

func (q *Queries) GetProgram(ctx context.Context, id string) (Program, error) {
	row := q.db.QueryRowContext(ctx, getProgram, id)
	var i Program
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.CycleID,
		&i.WeeklyLookupID,
		&i.DailyLookupID,
		&i.DefaultRounding,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProgramBySlug = `-- name: GetProgramBySlug :one
SELECT id, name, slug, description, cycle_id, weekly_lookup_id, daily_lookup_id, default_rounding, created_at, updated_at
FROM programs
WHERE slug = ?
`

func (q *Queries) GetProgramBySlug(ctx context.Context, slug string) (Program, error) {
	row := q.db.QueryRowContext(ctx, getProgramBySlug, slug)
	var i Program
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.CycleID,
		&i.WeeklyLookupID,
		&i.DailyLookupID,
		&i.DefaultRounding,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getWeeklyLookupForProgram = `-- name: GetWeeklyLookupForProgram :one
SELECT id, name, entries, program_id, created_at, updated_at
FROM weekly_lookups
WHERE id = ?
`

func (q *Queries) GetWeeklyLookupForProgram(ctx context.Context, id string) (WeeklyLookup, error) {
	row := q.db.QueryRowContext(ctx, getWeeklyLookupForProgram, id)
	var i WeeklyLookup
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Entries,
		&i.ProgramID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listProgramsByCreatedAtAsc = `-- name: ListProgramsByCreatedAtAsc :many
SELECT id, name, slug, description, cycle_id, weekly_lookup_id, daily_lookup_id, default_rounding, created_at, updated_at
FROM programs
ORDER BY created_at ASC
LIMIT ? OFFSET ?
`

type ListProgramsByCreatedAtAscParams struct {
	Limit  int64 `json:"limit"`
	Offset int64 `json:"offset"`
}

func (q *Queries) ListProgramsByCreatedAtAsc(ctx context.Context, arg ListProgramsByCreatedAtAscParams) ([]Program, error) {
	rows, err := q.db.QueryContext(ctx, listProgramsByCreatedAtAsc, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Program{}
	for rows.Next() {
		var i Program
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Description,
			&i.CycleID,
			&i.WeeklyLookupID,
			&i.DailyLookupID,
			&i.DefaultRounding,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProgramsByCreatedAtDesc = `-- name: ListProgramsByCreatedAtDesc :many
SELECT id, name, slug, description, cycle_id, weekly_lookup_id, daily_lookup_id, default_rounding, created_at, updated_at
FROM programs
ORDER BY created_at DESC
LIMIT ? OFFSET ?
`

type ListProgramsByCreatedAtDescParams struct {
	Limit  int64 `json:"limit"`
	Offset int64 `json:"offset"`
}

func (q *Queries) ListProgramsByCreatedAtDesc(ctx context.Context, arg ListProgramsByCreatedAtDescParams) ([]Program, error) {
	rows, err := q.db.QueryContext(ctx, listProgramsByCreatedAtDesc, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Program{}
	for rows.Next() {
		var i Program
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Description,
			&i.CycleID,
			&i.WeeklyLookupID,
			&i.DailyLookupID,
			&i.DefaultRounding,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProgramsByNameAsc = `-- name: ListProgramsByNameAsc :many
SELECT id, name, slug, description, cycle_id, weekly_lookup_id, daily_lookup_id, default_rounding, created_at, updated_at
FROM programs
ORDER BY name ASC
LIMIT ? OFFSET ?
`

type ListProgramsByNameAscParams struct {
	Limit  int64 `json:"limit"`
	Offset int64 `json:"offset"`
}

func (q *Queries) ListProgramsByNameAsc(ctx context.Context, arg ListProgramsByNameAscParams) ([]Program, error) {
	rows, err := q.db.QueryContext(ctx, listProgramsByNameAsc, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Program{}
	for rows.Next() {
		var i Program
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Description,
			&i.CycleID,
			&i.WeeklyLookupID,
			&i.DailyLookupID,
			&i.DefaultRounding,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProgramsByNameDesc = `-- name: ListProgramsByNameDesc :many
SELECT id, name, slug, description, cycle_id, weekly_lookup_id, daily_lookup_id, default_rounding, created_at, updated_at
FROM programs
ORDER BY name DESC
LIMIT ? OFFSET ?
`

type ListProgramsByNameDescParams struct {
	Limit  int64 `json:"limit"`
	Offset int64 `json:"offset"`
}

func (q *Queries) ListProgramsByNameDesc(ctx context.Context, arg ListProgramsByNameDescParams) ([]Program, error) {
	rows, err := q.db.QueryContext(ctx, listProgramsByNameDesc, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Program{}
	for rows.Next() {
		var i Program
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Description,
			&i.CycleID,
			&i.WeeklyLookupID,
			&i.DailyLookupID,
			&i.DefaultRounding,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const programHasEnrolledUsers = `-- name: ProgramHasEnrolledUsers :one
SELECT EXISTS(
    SELECT 1 FROM user_program_states ups
    WHERE ups.program_id = ?
) AS has_enrolled
`

func (q *Queries) ProgramHasEnrolledUsers(ctx context.Context, programID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, programHasEnrolledUsers, programID)
	var has_enrolled int64
	err := row.Scan(&has_enrolled)
	return has_enrolled, err
}

const programSlugExists = `-- name: ProgramSlugExists :one
SELECT EXISTS(
    SELECT 1 FROM programs WHERE slug = ?
) AS slug_exists
`

func (q *Queries) ProgramSlugExists(ctx context.Context, slug string) (int64, error) {
	row := q.db.QueryRowContext(ctx, programSlugExists, slug)
	var slug_exists int64
	err := row.Scan(&slug_exists)
	return slug_exists, err
}

const programSlugExistsExcluding = `-- name: ProgramSlugExistsExcluding :one
SELECT EXISTS(
    SELECT 1 FROM programs WHERE slug = ? AND id != ?
) AS slug_exists
`

type ProgramSlugExistsExcludingParams struct {
	Slug string `json:"slug"`
	ID   string `json:"id"`
}

func (q *Queries) ProgramSlugExistsExcluding(ctx context.Context, arg ProgramSlugExistsExcludingParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, programSlugExistsExcluding, arg.Slug, arg.ID)
	var slug_exists int64
	err := row.Scan(&slug_exists)
	return slug_exists, err
}

const updateProgram = `-- name: UpdateProgram :exec
UPDATE programs
SET name = ?, slug = ?, description = ?, cycle_id = ?, weekly_lookup_id = ?, daily_lookup_id = ?, default_rounding = ?, updated_at = ?
WHERE id = ?
`

type UpdateProgramParams struct {
	Name            string          `json:"name"`
	Slug            string          `json:"slug"`
	Description     sql.NullString  `json:"description"`
	CycleID         string          `json:"cycle_id"`
	WeeklyLookupID  sql.NullString  `json:"weekly_lookup_id"`
	DailyLookupID   sql.NullString  `json:"daily_lookup_id"`
	DefaultRounding sql.NullFloat64 `json:"default_rounding"`
	UpdatedAt       string          `json:"updated_at"`
	ID              string          `json:"id"`
}

func (q *Queries) UpdateProgram(ctx context.Context, arg UpdateProgramParams) error {
	_, err := q.db.ExecContext(ctx, updateProgram,
		arg.Name,
		arg.Slug,
		arg.Description,
		arg.CycleID,
		arg.WeeklyLookupID,
		arg.DailyLookupID,
		arg.DefaultRounding,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}
