// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
	"database/sql"
)

type Querier interface {
	CountCycles(ctx context.Context) (int64, error)
	CountDayPrescriptions(ctx context.Context, dayID string) (int64, error)
	CountDays(ctx context.Context) (int64, error)
	CountDaysFilteredByProgram(ctx context.Context, programID sql.NullString) (int64, error)
	CountLiftMaxesByUser(ctx context.Context, userID string) (int64, error)
	CountLiftMaxesByUserFilterLift(ctx context.Context, arg CountLiftMaxesByUserFilterLiftParams) (int64, error)
	CountLiftMaxesByUserFilterLiftAndType(ctx context.Context, arg CountLiftMaxesByUserFilterLiftAndTypeParams) (int64, error)
	CountLiftMaxesByUserFilterType(ctx context.Context, arg CountLiftMaxesByUserFilterTypeParams) (int64, error)
	CountLifts(ctx context.Context) (int64, error)
	CountLiftsFilteredByCompetition(ctx context.Context, isCompetitionLift int64) (int64, error)
	CountPrescriptions(ctx context.Context) (int64, error)
	CountPrescriptionsFilterLift(ctx context.Context, liftID string) (int64, error)
	CountWeekDays(ctx context.Context, weekID string) (int64, error)
	CountWeeks(ctx context.Context) (int64, error)
	CountWeeksByCycleID(ctx context.Context, cycleID string) (int64, error)
	CountWeeksFilteredByCycle(ctx context.Context, cycleID string) (int64, error)
	CreateCycle(ctx context.Context, arg CreateCycleParams) error
	CreateDay(ctx context.Context, arg CreateDayParams) error
	CreateDayPrescription(ctx context.Context, arg CreateDayPrescriptionParams) error
	CreateLift(ctx context.Context, arg CreateLiftParams) error
	CreateLiftMax(ctx context.Context, arg CreateLiftMaxParams) error
	CreatePrescription(ctx context.Context, arg CreatePrescriptionParams) error
	CreateUser(ctx context.Context, arg CreateUserParams) error
	CreateWeek(ctx context.Context, arg CreateWeekParams) error
	CreateWeekDay(ctx context.Context, arg CreateWeekDayParams) error
	CycleIsUsedByPrograms(ctx context.Context, cycleID string) (int64, error)
	DayIsUsedInWeeks(ctx context.Context, dayID string) (int64, error)
	DaySlugExists(ctx context.Context, arg DaySlugExistsParams) (int64, error)
	DaySlugExistsForNew(ctx context.Context, arg DaySlugExistsForNewParams) (int64, error)
	DaySlugExistsNullProgram(ctx context.Context, arg DaySlugExistsNullProgramParams) (int64, error)
	DaySlugExistsNullProgramForNew(ctx context.Context, slug string) (int64, error)
	DeleteCycle(ctx context.Context, id string) error
	DeleteDay(ctx context.Context, id string) error
	DeleteDayPrescription(ctx context.Context, id string) error
	DeleteDayPrescriptionByDayAndPrescription(ctx context.Context, arg DeleteDayPrescriptionByDayAndPrescriptionParams) error
	DeleteLift(ctx context.Context, id string) error
	DeleteLiftMax(ctx context.Context, id string) error
	DeletePrescription(ctx context.Context, id string) error
	DeleteWeek(ctx context.Context, id string) error
	DeleteWeekDay(ctx context.Context, id string) error
	DeleteWeekDayByWeekAndDay(ctx context.Context, arg DeleteWeekDayByWeekAndDayParams) error
	GetCurrentMax(ctx context.Context, arg GetCurrentMaxParams) (LiftMax, error)
	GetCurrentOneRM(ctx context.Context, arg GetCurrentOneRMParams) (LiftMax, error)
	GetCycle(ctx context.Context, id string) (Cycle, error)
	GetCycleByID(ctx context.Context, id string) (Cycle, error)
	GetDay(ctx context.Context, id string) (Day, error)
	GetDayBySlug(ctx context.Context, arg GetDayBySlugParams) (Day, error)
	// Day Prescriptions queries
	GetDayPrescription(ctx context.Context, id string) (DayPrescription, error)
	GetDayPrescriptionByDayAndPrescription(ctx context.Context, arg GetDayPrescriptionByDayAndPrescriptionParams) (DayPrescription, error)
	GetLift(ctx context.Context, id string) (Lift, error)
	GetLiftBySlug(ctx context.Context, slug string) (Lift, error)
	GetLiftMax(ctx context.Context, id string) (LiftMax, error)
	GetMaxDayPrescriptionOrder(ctx context.Context, dayID string) (interface{}, error)
	GetPrescription(ctx context.Context, id string) (Prescription, error)
	GetUser(ctx context.Context, id string) (User, error)
	GetWeek(ctx context.Context, id string) (Week, error)
	// Week Days queries
	GetWeekDay(ctx context.Context, id string) (WeekDay, error)
	GetWeekDayByWeekAndDayAndDayOfWeek(ctx context.Context, arg GetWeekDayByWeekAndDayAndDayOfWeekParams) (WeekDay, error)
	LiftHasChildReferences(ctx context.Context, parentLiftID sql.NullString) (int64, error)
	LiftHasMaxReferences(ctx context.Context, liftID string) (int64, error)
	LiftHasPrescriptionReferences(ctx context.Context, liftID string) (int64, error)
	ListCyclesByCreatedAtAsc(ctx context.Context, arg ListCyclesByCreatedAtAscParams) ([]Cycle, error)
	ListCyclesByCreatedAtDesc(ctx context.Context, arg ListCyclesByCreatedAtDescParams) ([]Cycle, error)
	ListCyclesByLengthWeeksAsc(ctx context.Context, arg ListCyclesByLengthWeeksAscParams) ([]Cycle, error)
	ListCyclesByLengthWeeksDesc(ctx context.Context, arg ListCyclesByLengthWeeksDescParams) ([]Cycle, error)
	ListCyclesByNameAsc(ctx context.Context, arg ListCyclesByNameAscParams) ([]Cycle, error)
	ListCyclesByNameDesc(ctx context.Context, arg ListCyclesByNameDescParams) ([]Cycle, error)
	ListDayPrescriptions(ctx context.Context, dayID string) ([]DayPrescription, error)
	ListDaysByCreatedAtAsc(ctx context.Context, arg ListDaysByCreatedAtAscParams) ([]Day, error)
	ListDaysByCreatedAtDesc(ctx context.Context, arg ListDaysByCreatedAtDescParams) ([]Day, error)
	ListDaysByNameAsc(ctx context.Context, arg ListDaysByNameAscParams) ([]Day, error)
	ListDaysByNameDesc(ctx context.Context, arg ListDaysByNameDescParams) ([]Day, error)
	ListDaysFilteredByProgramByCreatedAtAsc(ctx context.Context, arg ListDaysFilteredByProgramByCreatedAtAscParams) ([]Day, error)
	ListDaysFilteredByProgramByCreatedAtDesc(ctx context.Context, arg ListDaysFilteredByProgramByCreatedAtDescParams) ([]Day, error)
	ListDaysFilteredByProgramByNameAsc(ctx context.Context, arg ListDaysFilteredByProgramByNameAscParams) ([]Day, error)
	ListDaysFilteredByProgramByNameDesc(ctx context.Context, arg ListDaysFilteredByProgramByNameDescParams) ([]Day, error)
	ListLiftMaxesByUserByEffectiveDateAsc(ctx context.Context, arg ListLiftMaxesByUserByEffectiveDateAscParams) ([]LiftMax, error)
	ListLiftMaxesByUserByEffectiveDateDesc(ctx context.Context, arg ListLiftMaxesByUserByEffectiveDateDescParams) ([]LiftMax, error)
	ListLiftMaxesByUserFilterLiftAndTypeByEffectiveDateAsc(ctx context.Context, arg ListLiftMaxesByUserFilterLiftAndTypeByEffectiveDateAscParams) ([]LiftMax, error)
	ListLiftMaxesByUserFilterLiftAndTypeByEffectiveDateDesc(ctx context.Context, arg ListLiftMaxesByUserFilterLiftAndTypeByEffectiveDateDescParams) ([]LiftMax, error)
	ListLiftMaxesByUserFilterLiftByEffectiveDateAsc(ctx context.Context, arg ListLiftMaxesByUserFilterLiftByEffectiveDateAscParams) ([]LiftMax, error)
	ListLiftMaxesByUserFilterLiftByEffectiveDateDesc(ctx context.Context, arg ListLiftMaxesByUserFilterLiftByEffectiveDateDescParams) ([]LiftMax, error)
	ListLiftMaxesByUserFilterTypeByEffectiveDateAsc(ctx context.Context, arg ListLiftMaxesByUserFilterTypeByEffectiveDateAscParams) ([]LiftMax, error)
	ListLiftMaxesByUserFilterTypeByEffectiveDateDesc(ctx context.Context, arg ListLiftMaxesByUserFilterTypeByEffectiveDateDescParams) ([]LiftMax, error)
	ListLiftsByCreatedAtAsc(ctx context.Context, arg ListLiftsByCreatedAtAscParams) ([]Lift, error)
	ListLiftsByCreatedAtDesc(ctx context.Context, arg ListLiftsByCreatedAtDescParams) ([]Lift, error)
	ListLiftsByNameAsc(ctx context.Context, arg ListLiftsByNameAscParams) ([]Lift, error)
	ListLiftsByNameDesc(ctx context.Context, arg ListLiftsByNameDescParams) ([]Lift, error)
	ListLiftsFilteredByCompetitionByCreatedAtAsc(ctx context.Context, arg ListLiftsFilteredByCompetitionByCreatedAtAscParams) ([]Lift, error)
	ListLiftsFilteredByCompetitionByCreatedAtDesc(ctx context.Context, arg ListLiftsFilteredByCompetitionByCreatedAtDescParams) ([]Lift, error)
	ListLiftsFilteredByCompetitionByNameAsc(ctx context.Context, arg ListLiftsFilteredByCompetitionByNameAscParams) ([]Lift, error)
	ListLiftsFilteredByCompetitionByNameDesc(ctx context.Context, arg ListLiftsFilteredByCompetitionByNameDescParams) ([]Lift, error)
	ListPrescriptionsByCreatedAtAsc(ctx context.Context, arg ListPrescriptionsByCreatedAtAscParams) ([]Prescription, error)
	ListPrescriptionsByCreatedAtDesc(ctx context.Context, arg ListPrescriptionsByCreatedAtDescParams) ([]Prescription, error)
	ListPrescriptionsByOrderAsc(ctx context.Context, arg ListPrescriptionsByOrderAscParams) ([]Prescription, error)
	ListPrescriptionsByOrderDesc(ctx context.Context, arg ListPrescriptionsByOrderDescParams) ([]Prescription, error)
	ListPrescriptionsFilterLiftByCreatedAtAsc(ctx context.Context, arg ListPrescriptionsFilterLiftByCreatedAtAscParams) ([]Prescription, error)
	ListPrescriptionsFilterLiftByCreatedAtDesc(ctx context.Context, arg ListPrescriptionsFilterLiftByCreatedAtDescParams) ([]Prescription, error)
	ListPrescriptionsFilterLiftByOrderAsc(ctx context.Context, arg ListPrescriptionsFilterLiftByOrderAscParams) ([]Prescription, error)
	ListPrescriptionsFilterLiftByOrderDesc(ctx context.Context, arg ListPrescriptionsFilterLiftByOrderDescParams) ([]Prescription, error)
	ListWeekDays(ctx context.Context, weekID string) ([]WeekDay, error)
	ListWeeksByCreatedAtAsc(ctx context.Context, arg ListWeeksByCreatedAtAscParams) ([]Week, error)
	ListWeeksByCreatedAtDesc(ctx context.Context, arg ListWeeksByCreatedAtDescParams) ([]Week, error)
	ListWeeksByCycleID(ctx context.Context, cycleID string) ([]Week, error)
	ListWeeksByWeekNumberAsc(ctx context.Context, arg ListWeeksByWeekNumberAscParams) ([]Week, error)
	ListWeeksByWeekNumberDesc(ctx context.Context, arg ListWeeksByWeekNumberDescParams) ([]Week, error)
	ListWeeksFilteredByCycleByCreatedAtAsc(ctx context.Context, arg ListWeeksFilteredByCycleByCreatedAtAscParams) ([]Week, error)
	ListWeeksFilteredByCycleByCreatedAtDesc(ctx context.Context, arg ListWeeksFilteredByCycleByCreatedAtDescParams) ([]Week, error)
	ListWeeksFilteredByCycleByWeekNumberAsc(ctx context.Context, arg ListWeeksFilteredByCycleByWeekNumberAscParams) ([]Week, error)
	ListWeeksFilteredByCycleByWeekNumberDesc(ctx context.Context, arg ListWeeksFilteredByCycleByWeekNumberDescParams) ([]Week, error)
	SlugExists(ctx context.Context, arg SlugExistsParams) (int64, error)
	SlugExistsForNew(ctx context.Context, slug string) (int64, error)
	UniqueConstraintExists(ctx context.Context, arg UniqueConstraintExistsParams) (int64, error)
	UniqueConstraintExistsExcluding(ctx context.Context, arg UniqueConstraintExistsExcludingParams) (int64, error)
	UpdateCycle(ctx context.Context, arg UpdateCycleParams) error
	UpdateDay(ctx context.Context, arg UpdateDayParams) error
	UpdateDayPrescriptionOrder(ctx context.Context, arg UpdateDayPrescriptionOrderParams) error
	UpdateLift(ctx context.Context, arg UpdateLiftParams) error
	UpdateLiftMax(ctx context.Context, arg UpdateLiftMaxParams) error
	UpdatePrescription(ctx context.Context, arg UpdatePrescriptionParams) error
	UpdateWeek(ctx context.Context, arg UpdateWeekParams) error
	WeekIsUsedInActiveCycle(ctx context.Context, id string) (int64, error)
	WeekNumberExistsInCycle(ctx context.Context, arg WeekNumberExistsInCycleParams) (int64, error)
	WeekNumberExistsInCycleForNew(ctx context.Context, arg WeekNumberExistsInCycleForNewParams) (int64, error)
}

var _ Querier = (*Queries)(nil)
