// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
	"database/sql"
)

type Querier interface {
	CountLifts(ctx context.Context) (int64, error)
	CountLiftsFilteredByCompetition(ctx context.Context, isCompetitionLift int64) (int64, error)
	CreateLift(ctx context.Context, arg CreateLiftParams) error
	DeleteLift(ctx context.Context, id string) error
	GetLift(ctx context.Context, id string) (Lift, error)
	GetLiftBySlug(ctx context.Context, slug string) (Lift, error)
	LiftHasChildReferences(ctx context.Context, parentLiftID sql.NullString) (int64, error)
	ListLiftsByCreatedAtAsc(ctx context.Context, arg ListLiftsByCreatedAtAscParams) ([]Lift, error)
	ListLiftsByCreatedAtDesc(ctx context.Context, arg ListLiftsByCreatedAtDescParams) ([]Lift, error)
	ListLiftsByNameAsc(ctx context.Context, arg ListLiftsByNameAscParams) ([]Lift, error)
	ListLiftsByNameDesc(ctx context.Context, arg ListLiftsByNameDescParams) ([]Lift, error)
	ListLiftsFilteredByCompetitionByCreatedAtAsc(ctx context.Context, arg ListLiftsFilteredByCompetitionByCreatedAtAscParams) ([]Lift, error)
	ListLiftsFilteredByCompetitionByCreatedAtDesc(ctx context.Context, arg ListLiftsFilteredByCompetitionByCreatedAtDescParams) ([]Lift, error)
	ListLiftsFilteredByCompetitionByNameAsc(ctx context.Context, arg ListLiftsFilteredByCompetitionByNameAscParams) ([]Lift, error)
	ListLiftsFilteredByCompetitionByNameDesc(ctx context.Context, arg ListLiftsFilteredByCompetitionByNameDescParams) ([]Lift, error)
	SlugExists(ctx context.Context, arg SlugExistsParams) (int64, error)
	SlugExistsForNew(ctx context.Context, slug string) (int64, error)
	UpdateLift(ctx context.Context, arg UpdateLiftParams) error
}

var _ Querier = (*Queries)(nil)
