// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user_program_states.sql

package db

import (
	"context"
	"database/sql"
)

const createUserProgramState = `-- name: CreateUserProgramState :exec
INSERT INTO user_program_states (id, user_id, program_id, current_week, current_cycle_iteration, current_day_index, enrolled_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateUserProgramStateParams struct {
	ID                    string        `json:"id"`
	UserID                string        `json:"user_id"`
	ProgramID             string        `json:"program_id"`
	CurrentWeek           int64         `json:"current_week"`
	CurrentCycleIteration int64         `json:"current_cycle_iteration"`
	CurrentDayIndex       sql.NullInt64 `json:"current_day_index"`
	EnrolledAt            string        `json:"enrolled_at"`
	UpdatedAt             string        `json:"updated_at"`
}

func (q *Queries) CreateUserProgramState(ctx context.Context, arg CreateUserProgramStateParams) error {
	_, err := q.db.ExecContext(ctx, createUserProgramState,
		arg.ID,
		arg.UserID,
		arg.ProgramID,
		arg.CurrentWeek,
		arg.CurrentCycleIteration,
		arg.CurrentDayIndex,
		arg.EnrolledAt,
		arg.UpdatedAt,
	)
	return err
}

const deleteUserProgramStateByUserID = `-- name: DeleteUserProgramStateByUserID :exec
DELETE FROM user_program_states WHERE user_id = ?
`

func (q *Queries) DeleteUserProgramStateByUserID(ctx context.Context, userID string) error {
	_, err := q.db.ExecContext(ctx, deleteUserProgramStateByUserID, userID)
	return err
}

const getEnrollmentWithProgram = `-- name: GetEnrollmentWithProgram :one
SELECT
    ups.id,
    ups.user_id,
    ups.program_id,
    ups.current_week,
    ups.current_cycle_iteration,
    ups.current_day_index,
    ups.enrolled_at,
    ups.updated_at,
    p.name AS program_name,
    p.slug AS program_slug,
    p.description AS program_description,
    c.length_weeks AS cycle_length_weeks
FROM user_program_states ups
JOIN programs p ON ups.program_id = p.id
JOIN cycles c ON p.cycle_id = c.id
WHERE ups.user_id = ?
`

type GetEnrollmentWithProgramRow struct {
	ID                    string         `json:"id"`
	UserID                string         `json:"user_id"`
	ProgramID             string         `json:"program_id"`
	CurrentWeek           int64          `json:"current_week"`
	CurrentCycleIteration int64          `json:"current_cycle_iteration"`
	CurrentDayIndex       sql.NullInt64  `json:"current_day_index"`
	EnrolledAt            string         `json:"enrolled_at"`
	UpdatedAt             string         `json:"updated_at"`
	ProgramName           string         `json:"program_name"`
	ProgramSlug           string         `json:"program_slug"`
	ProgramDescription    sql.NullString `json:"program_description"`
	CycleLengthWeeks      int64          `json:"cycle_length_weeks"`
}

func (q *Queries) GetEnrollmentWithProgram(ctx context.Context, userID string) (GetEnrollmentWithProgramRow, error) {
	row := q.db.QueryRowContext(ctx, getEnrollmentWithProgram, userID)
	var i GetEnrollmentWithProgramRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ProgramID,
		&i.CurrentWeek,
		&i.CurrentCycleIteration,
		&i.CurrentDayIndex,
		&i.EnrolledAt,
		&i.UpdatedAt,
		&i.ProgramName,
		&i.ProgramSlug,
		&i.ProgramDescription,
		&i.CycleLengthWeeks,
	)
	return i, err
}

const getStateAdvancementContext = `-- name: GetStateAdvancementContext :one
SELECT
    ups.id,
    ups.user_id,
    ups.program_id,
    ups.current_week,
    ups.current_cycle_iteration,
    ups.current_day_index,
    ups.enrolled_at,
    ups.updated_at,
    c.id AS cycle_id,
    c.length_weeks AS cycle_length_weeks,
    (
        SELECT COUNT(*)
        FROM week_days wd
        JOIN weeks w ON wd.week_id = w.id
        WHERE w.cycle_id = c.id AND w.week_number = ups.current_week
    ) AS days_in_current_week
FROM user_program_states ups
JOIN programs p ON ups.program_id = p.id
JOIN cycles c ON p.cycle_id = c.id
WHERE ups.user_id = ?
`

type GetStateAdvancementContextRow struct {
	ID                    string        `json:"id"`
	UserID                string        `json:"user_id"`
	ProgramID             string        `json:"program_id"`
	CurrentWeek           int64         `json:"current_week"`
	CurrentCycleIteration int64         `json:"current_cycle_iteration"`
	CurrentDayIndex       sql.NullInt64 `json:"current_day_index"`
	EnrolledAt            string        `json:"enrolled_at"`
	UpdatedAt             string        `json:"updated_at"`
	CycleID               string        `json:"cycle_id"`
	CycleLengthWeeks      int64         `json:"cycle_length_weeks"`
	DaysInCurrentWeek     int64         `json:"days_in_current_week"`
}

func (q *Queries) GetStateAdvancementContext(ctx context.Context, userID string) (GetStateAdvancementContextRow, error) {
	row := q.db.QueryRowContext(ctx, getStateAdvancementContext, userID)
	var i GetStateAdvancementContextRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ProgramID,
		&i.CurrentWeek,
		&i.CurrentCycleIteration,
		&i.CurrentDayIndex,
		&i.EnrolledAt,
		&i.UpdatedAt,
		&i.CycleID,
		&i.CycleLengthWeeks,
		&i.DaysInCurrentWeek,
	)
	return i, err
}

const getUserProgramStateByID = `-- name: GetUserProgramStateByID :one
SELECT id, user_id, program_id, current_week, current_cycle_iteration, current_day_index, enrolled_at, updated_at
FROM user_program_states
WHERE id = ?
`

type GetUserProgramStateByIDRow struct {
	ID                    string        `json:"id"`
	UserID                string        `json:"user_id"`
	ProgramID             string        `json:"program_id"`
	CurrentWeek           int64         `json:"current_week"`
	CurrentCycleIteration int64         `json:"current_cycle_iteration"`
	CurrentDayIndex       sql.NullInt64 `json:"current_day_index"`
	EnrolledAt            string        `json:"enrolled_at"`
	UpdatedAt             string        `json:"updated_at"`
}

func (q *Queries) GetUserProgramStateByID(ctx context.Context, id string) (GetUserProgramStateByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getUserProgramStateByID, id)
	var i GetUserProgramStateByIDRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ProgramID,
		&i.CurrentWeek,
		&i.CurrentCycleIteration,
		&i.CurrentDayIndex,
		&i.EnrolledAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserProgramStateByUserID = `-- name: GetUserProgramStateByUserID :one
SELECT id, user_id, program_id, current_week, current_cycle_iteration, current_day_index, enrolled_at, updated_at
FROM user_program_states
WHERE user_id = ?
`

type GetUserProgramStateByUserIDRow struct {
	ID                    string        `json:"id"`
	UserID                string        `json:"user_id"`
	ProgramID             string        `json:"program_id"`
	CurrentWeek           int64         `json:"current_week"`
	CurrentCycleIteration int64         `json:"current_cycle_iteration"`
	CurrentDayIndex       sql.NullInt64 `json:"current_day_index"`
	EnrolledAt            string        `json:"enrolled_at"`
	UpdatedAt             string        `json:"updated_at"`
}

func (q *Queries) GetUserProgramStateByUserID(ctx context.Context, userID string) (GetUserProgramStateByUserIDRow, error) {
	row := q.db.QueryRowContext(ctx, getUserProgramStateByUserID, userID)
	var i GetUserProgramStateByUserIDRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ProgramID,
		&i.CurrentWeek,
		&i.CurrentCycleIteration,
		&i.CurrentDayIndex,
		&i.EnrolledAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUserProgramState = `-- name: UpdateUserProgramState :exec
UPDATE user_program_states
SET program_id = ?, current_week = ?, current_cycle_iteration = ?, current_day_index = ?, updated_at = ?
WHERE user_id = ?
`

type UpdateUserProgramStateParams struct {
	ProgramID             string        `json:"program_id"`
	CurrentWeek           int64         `json:"current_week"`
	CurrentCycleIteration int64         `json:"current_cycle_iteration"`
	CurrentDayIndex       sql.NullInt64 `json:"current_day_index"`
	UpdatedAt             string        `json:"updated_at"`
	UserID                string        `json:"user_id"`
}

func (q *Queries) UpdateUserProgramState(ctx context.Context, arg UpdateUserProgramStateParams) error {
	_, err := q.db.ExecContext(ctx, updateUserProgramState,
		arg.ProgramID,
		arg.CurrentWeek,
		arg.CurrentCycleIteration,
		arg.CurrentDayIndex,
		arg.UpdatedAt,
		arg.UserID,
	)
	return err
}

const userIsEnrolled = `-- name: UserIsEnrolled :one
SELECT EXISTS(
    SELECT 1 FROM user_program_states WHERE user_id = ?
) AS is_enrolled
`

func (q *Queries) UserIsEnrolled(ctx context.Context, userID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, userIsEnrolled, userID)
	var is_enrolled int64
	err := row.Scan(&is_enrolled)
	return is_enrolled, err
}
