// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: weekly_lookups.sql

package db

import (
	"context"
	"database/sql"
)

const countWeeklyLookups = `-- name: CountWeeklyLookups :one
SELECT COUNT(*) FROM weekly_lookups
`

func (q *Queries) CountWeeklyLookups(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countWeeklyLookups)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createWeeklyLookup = `-- name: CreateWeeklyLookup :exec
INSERT INTO weekly_lookups (id, name, entries, program_id, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?)
`

type CreateWeeklyLookupParams struct {
	ID        string         `json:"id"`
	Name      string         `json:"name"`
	Entries   string         `json:"entries"`
	ProgramID sql.NullString `json:"program_id"`
	CreatedAt string         `json:"created_at"`
	UpdatedAt string         `json:"updated_at"`
}

func (q *Queries) CreateWeeklyLookup(ctx context.Context, arg CreateWeeklyLookupParams) error {
	_, err := q.db.ExecContext(ctx, createWeeklyLookup,
		arg.ID,
		arg.Name,
		arg.Entries,
		arg.ProgramID,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const deleteWeeklyLookup = `-- name: DeleteWeeklyLookup :exec
DELETE FROM weekly_lookups WHERE id = ?
`

func (q *Queries) DeleteWeeklyLookup(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteWeeklyLookup, id)
	return err
}

const getWeeklyLookup = `-- name: GetWeeklyLookup :one
SELECT id, name, entries, program_id, created_at, updated_at
FROM weekly_lookups
WHERE id = ?
`

func (q *Queries) GetWeeklyLookup(ctx context.Context, id string) (WeeklyLookup, error) {
	row := q.db.QueryRowContext(ctx, getWeeklyLookup, id)
	var i WeeklyLookup
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Entries,
		&i.ProgramID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listWeeklyLookupsByCreatedAtAsc = `-- name: ListWeeklyLookupsByCreatedAtAsc :many
SELECT id, name, entries, program_id, created_at, updated_at
FROM weekly_lookups
ORDER BY created_at ASC
LIMIT ? OFFSET ?
`

type ListWeeklyLookupsByCreatedAtAscParams struct {
	Limit  int64 `json:"limit"`
	Offset int64 `json:"offset"`
}

func (q *Queries) ListWeeklyLookupsByCreatedAtAsc(ctx context.Context, arg ListWeeklyLookupsByCreatedAtAscParams) ([]WeeklyLookup, error) {
	rows, err := q.db.QueryContext(ctx, listWeeklyLookupsByCreatedAtAsc, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WeeklyLookup{}
	for rows.Next() {
		var i WeeklyLookup
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Entries,
			&i.ProgramID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWeeklyLookupsByCreatedAtDesc = `-- name: ListWeeklyLookupsByCreatedAtDesc :many
SELECT id, name, entries, program_id, created_at, updated_at
FROM weekly_lookups
ORDER BY created_at DESC
LIMIT ? OFFSET ?
`

type ListWeeklyLookupsByCreatedAtDescParams struct {
	Limit  int64 `json:"limit"`
	Offset int64 `json:"offset"`
}

func (q *Queries) ListWeeklyLookupsByCreatedAtDesc(ctx context.Context, arg ListWeeklyLookupsByCreatedAtDescParams) ([]WeeklyLookup, error) {
	rows, err := q.db.QueryContext(ctx, listWeeklyLookupsByCreatedAtDesc, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WeeklyLookup{}
	for rows.Next() {
		var i WeeklyLookup
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Entries,
			&i.ProgramID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWeeklyLookupsByNameAsc = `-- name: ListWeeklyLookupsByNameAsc :many
SELECT id, name, entries, program_id, created_at, updated_at
FROM weekly_lookups
ORDER BY name ASC
LIMIT ? OFFSET ?
`

type ListWeeklyLookupsByNameAscParams struct {
	Limit  int64 `json:"limit"`
	Offset int64 `json:"offset"`
}

func (q *Queries) ListWeeklyLookupsByNameAsc(ctx context.Context, arg ListWeeklyLookupsByNameAscParams) ([]WeeklyLookup, error) {
	rows, err := q.db.QueryContext(ctx, listWeeklyLookupsByNameAsc, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WeeklyLookup{}
	for rows.Next() {
		var i WeeklyLookup
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Entries,
			&i.ProgramID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWeeklyLookupsByNameDesc = `-- name: ListWeeklyLookupsByNameDesc :many
SELECT id, name, entries, program_id, created_at, updated_at
FROM weekly_lookups
ORDER BY name DESC
LIMIT ? OFFSET ?
`

type ListWeeklyLookupsByNameDescParams struct {
	Limit  int64 `json:"limit"`
	Offset int64 `json:"offset"`
}

func (q *Queries) ListWeeklyLookupsByNameDesc(ctx context.Context, arg ListWeeklyLookupsByNameDescParams) ([]WeeklyLookup, error) {
	rows, err := q.db.QueryContext(ctx, listWeeklyLookupsByNameDesc, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WeeklyLookup{}
	for rows.Next() {
		var i WeeklyLookup
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Entries,
			&i.ProgramID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateWeeklyLookup = `-- name: UpdateWeeklyLookup :exec
UPDATE weekly_lookups
SET name = ?, entries = ?, program_id = ?, updated_at = ?
WHERE id = ?
`

type UpdateWeeklyLookupParams struct {
	Name      string         `json:"name"`
	Entries   string         `json:"entries"`
	ProgramID sql.NullString `json:"program_id"`
	UpdatedAt string         `json:"updated_at"`
	ID        string         `json:"id"`
}

func (q *Queries) UpdateWeeklyLookup(ctx context.Context, arg UpdateWeeklyLookupParams) error {
	_, err := q.db.ExecContext(ctx, updateWeeklyLookup,
		arg.Name,
		arg.Entries,
		arg.ProgramID,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}

const weeklyLookupIsUsedByPrograms = `-- name: WeeklyLookupIsUsedByPrograms :one
SELECT EXISTS(
    SELECT 1 FROM programs p
    WHERE p.weekly_lookup_id = ?
) AS is_used
`

func (q *Queries) WeeklyLookupIsUsedByPrograms(ctx context.Context, weeklyLookupID sql.NullString) (int64, error) {
	row := q.db.QueryRowContext(ctx, weeklyLookupIsUsedByPrograms, weeklyLookupID)
	var is_used int64
	err := row.Scan(&is_used)
	return is_used, err
}
