// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: weeks.sql

package db

import (
	"context"
	"database/sql"
)

const countWeekDays = `-- name: CountWeekDays :one
SELECT COUNT(*) FROM week_days WHERE week_id = ?
`

func (q *Queries) CountWeekDays(ctx context.Context, weekID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countWeekDays, weekID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countWeeks = `-- name: CountWeeks :one
SELECT COUNT(*) FROM weeks
`

func (q *Queries) CountWeeks(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countWeeks)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countWeeksFilteredByCycle = `-- name: CountWeeksFilteredByCycle :one
SELECT COUNT(*) FROM weeks WHERE cycle_id = ?
`

func (q *Queries) CountWeeksFilteredByCycle(ctx context.Context, cycleID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countWeeksFilteredByCycle, cycleID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createWeek = `-- name: CreateWeek :exec
INSERT INTO weeks (id, week_number, variant, cycle_id, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?)
`

type CreateWeekParams struct {
	ID         string         `json:"id"`
	WeekNumber int64          `json:"week_number"`
	Variant    sql.NullString `json:"variant"`
	CycleID    string         `json:"cycle_id"`
	CreatedAt  string         `json:"created_at"`
	UpdatedAt  string         `json:"updated_at"`
}

func (q *Queries) CreateWeek(ctx context.Context, arg CreateWeekParams) error {
	_, err := q.db.ExecContext(ctx, createWeek,
		arg.ID,
		arg.WeekNumber,
		arg.Variant,
		arg.CycleID,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const createWeekDay = `-- name: CreateWeekDay :exec
INSERT INTO week_days (id, week_id, day_id, day_of_week, created_at)
VALUES (?, ?, ?, ?, ?)
`

type CreateWeekDayParams struct {
	ID        string `json:"id"`
	WeekID    string `json:"week_id"`
	DayID     string `json:"day_id"`
	DayOfWeek string `json:"day_of_week"`
	CreatedAt string `json:"created_at"`
}

func (q *Queries) CreateWeekDay(ctx context.Context, arg CreateWeekDayParams) error {
	_, err := q.db.ExecContext(ctx, createWeekDay,
		arg.ID,
		arg.WeekID,
		arg.DayID,
		arg.DayOfWeek,
		arg.CreatedAt,
	)
	return err
}

const deleteWeek = `-- name: DeleteWeek :exec
DELETE FROM weeks WHERE id = ?
`

func (q *Queries) DeleteWeek(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteWeek, id)
	return err
}

const deleteWeekDay = `-- name: DeleteWeekDay :exec
DELETE FROM week_days WHERE id = ?
`

func (q *Queries) DeleteWeekDay(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteWeekDay, id)
	return err
}

const deleteWeekDayByWeekAndDay = `-- name: DeleteWeekDayByWeekAndDay :exec
DELETE FROM week_days WHERE week_id = ? AND day_id = ? AND day_of_week = ?
`

type DeleteWeekDayByWeekAndDayParams struct {
	WeekID    string `json:"week_id"`
	DayID     string `json:"day_id"`
	DayOfWeek string `json:"day_of_week"`
}

func (q *Queries) DeleteWeekDayByWeekAndDay(ctx context.Context, arg DeleteWeekDayByWeekAndDayParams) error {
	_, err := q.db.ExecContext(ctx, deleteWeekDayByWeekAndDay, arg.WeekID, arg.DayID, arg.DayOfWeek)
	return err
}

const getCycleByID = `-- name: GetCycleByID :one
SELECT id, name, length_weeks, created_at, updated_at
FROM cycles
WHERE id = ?
`

func (q *Queries) GetCycleByID(ctx context.Context, id string) (Cycle, error) {
	row := q.db.QueryRowContext(ctx, getCycleByID, id)
	var i Cycle
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.LengthWeeks,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getWeek = `-- name: GetWeek :one
SELECT id, week_number, variant, cycle_id, created_at, updated_at
FROM weeks
WHERE id = ?
`

func (q *Queries) GetWeek(ctx context.Context, id string) (Week, error) {
	row := q.db.QueryRowContext(ctx, getWeek, id)
	var i Week
	err := row.Scan(
		&i.ID,
		&i.WeekNumber,
		&i.Variant,
		&i.CycleID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getWeekDay = `-- name: GetWeekDay :one

SELECT id, week_id, day_id, day_of_week, created_at
FROM week_days
WHERE id = ?
`

// Week Days queries
func (q *Queries) GetWeekDay(ctx context.Context, id string) (WeekDay, error) {
	row := q.db.QueryRowContext(ctx, getWeekDay, id)
	var i WeekDay
	err := row.Scan(
		&i.ID,
		&i.WeekID,
		&i.DayID,
		&i.DayOfWeek,
		&i.CreatedAt,
	)
	return i, err
}

const getWeekDayByWeekAndDayAndDayOfWeek = `-- name: GetWeekDayByWeekAndDayAndDayOfWeek :one
SELECT id, week_id, day_id, day_of_week, created_at
FROM week_days
WHERE week_id = ? AND day_id = ? AND day_of_week = ?
`

type GetWeekDayByWeekAndDayAndDayOfWeekParams struct {
	WeekID    string `json:"week_id"`
	DayID     string `json:"day_id"`
	DayOfWeek string `json:"day_of_week"`
}

func (q *Queries) GetWeekDayByWeekAndDayAndDayOfWeek(ctx context.Context, arg GetWeekDayByWeekAndDayAndDayOfWeekParams) (WeekDay, error) {
	row := q.db.QueryRowContext(ctx, getWeekDayByWeekAndDayAndDayOfWeek, arg.WeekID, arg.DayID, arg.DayOfWeek)
	var i WeekDay
	err := row.Scan(
		&i.ID,
		&i.WeekID,
		&i.DayID,
		&i.DayOfWeek,
		&i.CreatedAt,
	)
	return i, err
}

const listWeekDays = `-- name: ListWeekDays :many
SELECT wd.id, wd.week_id, wd.day_id, wd.day_of_week, wd.created_at
FROM week_days wd
WHERE wd.week_id = ?
ORDER BY
    CASE wd.day_of_week
        WHEN 'MONDAY' THEN 1
        WHEN 'TUESDAY' THEN 2
        WHEN 'WEDNESDAY' THEN 3
        WHEN 'THURSDAY' THEN 4
        WHEN 'FRIDAY' THEN 5
        WHEN 'SATURDAY' THEN 6
        WHEN 'SUNDAY' THEN 7
    END ASC
`

func (q *Queries) ListWeekDays(ctx context.Context, weekID string) ([]WeekDay, error) {
	rows, err := q.db.QueryContext(ctx, listWeekDays, weekID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WeekDay{}
	for rows.Next() {
		var i WeekDay
		if err := rows.Scan(
			&i.ID,
			&i.WeekID,
			&i.DayID,
			&i.DayOfWeek,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWeeksByCreatedAtAsc = `-- name: ListWeeksByCreatedAtAsc :many
SELECT id, week_number, variant, cycle_id, created_at, updated_at
FROM weeks
ORDER BY created_at ASC
LIMIT ? OFFSET ?
`

type ListWeeksByCreatedAtAscParams struct {
	Limit  int64 `json:"limit"`
	Offset int64 `json:"offset"`
}

func (q *Queries) ListWeeksByCreatedAtAsc(ctx context.Context, arg ListWeeksByCreatedAtAscParams) ([]Week, error) {
	rows, err := q.db.QueryContext(ctx, listWeeksByCreatedAtAsc, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Week{}
	for rows.Next() {
		var i Week
		if err := rows.Scan(
			&i.ID,
			&i.WeekNumber,
			&i.Variant,
			&i.CycleID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWeeksByCreatedAtDesc = `-- name: ListWeeksByCreatedAtDesc :many
SELECT id, week_number, variant, cycle_id, created_at, updated_at
FROM weeks
ORDER BY created_at DESC
LIMIT ? OFFSET ?
`

type ListWeeksByCreatedAtDescParams struct {
	Limit  int64 `json:"limit"`
	Offset int64 `json:"offset"`
}

func (q *Queries) ListWeeksByCreatedAtDesc(ctx context.Context, arg ListWeeksByCreatedAtDescParams) ([]Week, error) {
	rows, err := q.db.QueryContext(ctx, listWeeksByCreatedAtDesc, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Week{}
	for rows.Next() {
		var i Week
		if err := rows.Scan(
			&i.ID,
			&i.WeekNumber,
			&i.Variant,
			&i.CycleID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWeeksByWeekNumberAsc = `-- name: ListWeeksByWeekNumberAsc :many
SELECT id, week_number, variant, cycle_id, created_at, updated_at
FROM weeks
ORDER BY week_number ASC
LIMIT ? OFFSET ?
`

type ListWeeksByWeekNumberAscParams struct {
	Limit  int64 `json:"limit"`
	Offset int64 `json:"offset"`
}

func (q *Queries) ListWeeksByWeekNumberAsc(ctx context.Context, arg ListWeeksByWeekNumberAscParams) ([]Week, error) {
	rows, err := q.db.QueryContext(ctx, listWeeksByWeekNumberAsc, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Week{}
	for rows.Next() {
		var i Week
		if err := rows.Scan(
			&i.ID,
			&i.WeekNumber,
			&i.Variant,
			&i.CycleID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWeeksByWeekNumberDesc = `-- name: ListWeeksByWeekNumberDesc :many
SELECT id, week_number, variant, cycle_id, created_at, updated_at
FROM weeks
ORDER BY week_number DESC
LIMIT ? OFFSET ?
`

type ListWeeksByWeekNumberDescParams struct {
	Limit  int64 `json:"limit"`
	Offset int64 `json:"offset"`
}

func (q *Queries) ListWeeksByWeekNumberDesc(ctx context.Context, arg ListWeeksByWeekNumberDescParams) ([]Week, error) {
	rows, err := q.db.QueryContext(ctx, listWeeksByWeekNumberDesc, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Week{}
	for rows.Next() {
		var i Week
		if err := rows.Scan(
			&i.ID,
			&i.WeekNumber,
			&i.Variant,
			&i.CycleID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWeeksFilteredByCycleByCreatedAtAsc = `-- name: ListWeeksFilteredByCycleByCreatedAtAsc :many
SELECT id, week_number, variant, cycle_id, created_at, updated_at
FROM weeks
WHERE cycle_id = ?
ORDER BY created_at ASC
LIMIT ? OFFSET ?
`

type ListWeeksFilteredByCycleByCreatedAtAscParams struct {
	CycleID string `json:"cycle_id"`
	Limit   int64  `json:"limit"`
	Offset  int64  `json:"offset"`
}

func (q *Queries) ListWeeksFilteredByCycleByCreatedAtAsc(ctx context.Context, arg ListWeeksFilteredByCycleByCreatedAtAscParams) ([]Week, error) {
	rows, err := q.db.QueryContext(ctx, listWeeksFilteredByCycleByCreatedAtAsc, arg.CycleID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Week{}
	for rows.Next() {
		var i Week
		if err := rows.Scan(
			&i.ID,
			&i.WeekNumber,
			&i.Variant,
			&i.CycleID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWeeksFilteredByCycleByCreatedAtDesc = `-- name: ListWeeksFilteredByCycleByCreatedAtDesc :many
SELECT id, week_number, variant, cycle_id, created_at, updated_at
FROM weeks
WHERE cycle_id = ?
ORDER BY created_at DESC
LIMIT ? OFFSET ?
`

type ListWeeksFilteredByCycleByCreatedAtDescParams struct {
	CycleID string `json:"cycle_id"`
	Limit   int64  `json:"limit"`
	Offset  int64  `json:"offset"`
}

func (q *Queries) ListWeeksFilteredByCycleByCreatedAtDesc(ctx context.Context, arg ListWeeksFilteredByCycleByCreatedAtDescParams) ([]Week, error) {
	rows, err := q.db.QueryContext(ctx, listWeeksFilteredByCycleByCreatedAtDesc, arg.CycleID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Week{}
	for rows.Next() {
		var i Week
		if err := rows.Scan(
			&i.ID,
			&i.WeekNumber,
			&i.Variant,
			&i.CycleID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWeeksFilteredByCycleByWeekNumberAsc = `-- name: ListWeeksFilteredByCycleByWeekNumberAsc :many
SELECT id, week_number, variant, cycle_id, created_at, updated_at
FROM weeks
WHERE cycle_id = ?
ORDER BY week_number ASC
LIMIT ? OFFSET ?
`

type ListWeeksFilteredByCycleByWeekNumberAscParams struct {
	CycleID string `json:"cycle_id"`
	Limit   int64  `json:"limit"`
	Offset  int64  `json:"offset"`
}

func (q *Queries) ListWeeksFilteredByCycleByWeekNumberAsc(ctx context.Context, arg ListWeeksFilteredByCycleByWeekNumberAscParams) ([]Week, error) {
	rows, err := q.db.QueryContext(ctx, listWeeksFilteredByCycleByWeekNumberAsc, arg.CycleID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Week{}
	for rows.Next() {
		var i Week
		if err := rows.Scan(
			&i.ID,
			&i.WeekNumber,
			&i.Variant,
			&i.CycleID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWeeksFilteredByCycleByWeekNumberDesc = `-- name: ListWeeksFilteredByCycleByWeekNumberDesc :many
SELECT id, week_number, variant, cycle_id, created_at, updated_at
FROM weeks
WHERE cycle_id = ?
ORDER BY week_number DESC
LIMIT ? OFFSET ?
`

type ListWeeksFilteredByCycleByWeekNumberDescParams struct {
	CycleID string `json:"cycle_id"`
	Limit   int64  `json:"limit"`
	Offset  int64  `json:"offset"`
}

func (q *Queries) ListWeeksFilteredByCycleByWeekNumberDesc(ctx context.Context, arg ListWeeksFilteredByCycleByWeekNumberDescParams) ([]Week, error) {
	rows, err := q.db.QueryContext(ctx, listWeeksFilteredByCycleByWeekNumberDesc, arg.CycleID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Week{}
	for rows.Next() {
		var i Week
		if err := rows.Scan(
			&i.ID,
			&i.WeekNumber,
			&i.Variant,
			&i.CycleID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateWeek = `-- name: UpdateWeek :exec
UPDATE weeks
SET week_number = ?, variant = ?, cycle_id = ?, updated_at = ?
WHERE id = ?
`

type UpdateWeekParams struct {
	WeekNumber int64          `json:"week_number"`
	Variant    sql.NullString `json:"variant"`
	CycleID    string         `json:"cycle_id"`
	UpdatedAt  string         `json:"updated_at"`
	ID         string         `json:"id"`
}

func (q *Queries) UpdateWeek(ctx context.Context, arg UpdateWeekParams) error {
	_, err := q.db.ExecContext(ctx, updateWeek,
		arg.WeekNumber,
		arg.Variant,
		arg.CycleID,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}

const weekIsUsedInActiveCycle = `-- name: WeekIsUsedInActiveCycle :one
SELECT EXISTS(
    SELECT 1 FROM user_program_states ups
    JOIN programs p ON ups.program_id = p.id
    JOIN cycles c ON p.cycle_id = c.id
    JOIN weeks w ON w.cycle_id = c.id
    WHERE w.id = ?
) AS is_used
`

func (q *Queries) WeekIsUsedInActiveCycle(ctx context.Context, id string) (int64, error) {
	row := q.db.QueryRowContext(ctx, weekIsUsedInActiveCycle, id)
	var is_used int64
	err := row.Scan(&is_used)
	return is_used, err
}

const weekNumberExistsInCycle = `-- name: WeekNumberExistsInCycle :one
SELECT EXISTS(SELECT 1 FROM weeks WHERE cycle_id = ? AND week_number = ? AND id != ?) AS week_number_exists
`

type WeekNumberExistsInCycleParams struct {
	CycleID    string `json:"cycle_id"`
	WeekNumber int64  `json:"week_number"`
	ID         string `json:"id"`
}

func (q *Queries) WeekNumberExistsInCycle(ctx context.Context, arg WeekNumberExistsInCycleParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, weekNumberExistsInCycle, arg.CycleID, arg.WeekNumber, arg.ID)
	var week_number_exists int64
	err := row.Scan(&week_number_exists)
	return week_number_exists, err
}

const weekNumberExistsInCycleForNew = `-- name: WeekNumberExistsInCycleForNew :one
SELECT EXISTS(SELECT 1 FROM weeks WHERE cycle_id = ? AND week_number = ?) AS week_number_exists
`

type WeekNumberExistsInCycleForNewParams struct {
	CycleID    string `json:"cycle_id"`
	WeekNumber int64  `json:"week_number"`
}

func (q *Queries) WeekNumberExistsInCycleForNew(ctx context.Context, arg WeekNumberExistsInCycleForNewParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, weekNumberExistsInCycleForNew, arg.CycleID, arg.WeekNumber)
	var week_number_exists int64
	err := row.Scan(&week_number_exists)
	return week_number_exists, err
}
