// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: workout_sessions.sql

package db

import (
	"context"
	"database/sql"
)

const abandonWorkoutSession = `-- name: AbandonWorkoutSession :exec
UPDATE workout_sessions
SET status = 'ABANDONED', finished_at = ?, updated_at = ?
WHERE id = ?
`

type AbandonWorkoutSessionParams struct {
	FinishedAt sql.NullString `json:"finished_at"`
	UpdatedAt  string         `json:"updated_at"`
	ID         string         `json:"id"`
}

func (q *Queries) AbandonWorkoutSession(ctx context.Context, arg AbandonWorkoutSessionParams) error {
	_, err := q.db.ExecContext(ctx, abandonWorkoutSession, arg.FinishedAt, arg.UpdatedAt, arg.ID)
	return err
}

const completeWorkoutSession = `-- name: CompleteWorkoutSession :exec
UPDATE workout_sessions
SET status = 'COMPLETED', finished_at = ?, updated_at = ?
WHERE id = ?
`

type CompleteWorkoutSessionParams struct {
	FinishedAt sql.NullString `json:"finished_at"`
	UpdatedAt  string         `json:"updated_at"`
	ID         string         `json:"id"`
}

func (q *Queries) CompleteWorkoutSession(ctx context.Context, arg CompleteWorkoutSessionParams) error {
	_, err := q.db.ExecContext(ctx, completeWorkoutSession, arg.FinishedAt, arg.UpdatedAt, arg.ID)
	return err
}

const createWorkoutSession = `-- name: CreateWorkoutSession :exec
INSERT INTO workout_sessions (id, user_program_state_id, week_number, day_index, status, started_at, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateWorkoutSessionParams struct {
	ID                 string `json:"id"`
	UserProgramStateID string `json:"user_program_state_id"`
	WeekNumber         int64  `json:"week_number"`
	DayIndex           int64  `json:"day_index"`
	Status             string `json:"status"`
	StartedAt          string `json:"started_at"`
	CreatedAt          string `json:"created_at"`
	UpdatedAt          string `json:"updated_at"`
}

func (q *Queries) CreateWorkoutSession(ctx context.Context, arg CreateWorkoutSessionParams) error {
	_, err := q.db.ExecContext(ctx, createWorkoutSession,
		arg.ID,
		arg.UserProgramStateID,
		arg.WeekNumber,
		arg.DayIndex,
		arg.Status,
		arg.StartedAt,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const deleteWorkoutSession = `-- name: DeleteWorkoutSession :exec
DELETE FROM workout_sessions WHERE id = ?
`

func (q *Queries) DeleteWorkoutSession(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteWorkoutSession, id)
	return err
}

const getActiveWorkoutSession = `-- name: GetActiveWorkoutSession :one
SELECT id, user_program_state_id, week_number, day_index, status, started_at, finished_at, created_at, updated_at
FROM workout_sessions
WHERE user_program_state_id = ? AND status = 'IN_PROGRESS'
LIMIT 1
`

func (q *Queries) GetActiveWorkoutSession(ctx context.Context, userProgramStateID string) (WorkoutSession, error) {
	row := q.db.QueryRowContext(ctx, getActiveWorkoutSession, userProgramStateID)
	var i WorkoutSession
	err := row.Scan(
		&i.ID,
		&i.UserProgramStateID,
		&i.WeekNumber,
		&i.DayIndex,
		&i.Status,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getWorkoutSessionByID = `-- name: GetWorkoutSessionByID :one
SELECT id, user_program_state_id, week_number, day_index, status, started_at, finished_at, created_at, updated_at
FROM workout_sessions
WHERE id = ?
`

func (q *Queries) GetWorkoutSessionByID(ctx context.Context, id string) (WorkoutSession, error) {
	row := q.db.QueryRowContext(ctx, getWorkoutSessionByID, id)
	var i WorkoutSession
	err := row.Scan(
		&i.ID,
		&i.UserProgramStateID,
		&i.WeekNumber,
		&i.DayIndex,
		&i.Status,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getWorkoutSessionsByState = `-- name: GetWorkoutSessionsByState :many
SELECT id, user_program_state_id, week_number, day_index, status, started_at, finished_at, created_at, updated_at
FROM workout_sessions
WHERE user_program_state_id = ?
ORDER BY created_at DESC
`

func (q *Queries) GetWorkoutSessionsByState(ctx context.Context, userProgramStateID string) ([]WorkoutSession, error) {
	rows, err := q.db.QueryContext(ctx, getWorkoutSessionsByState, userProgramStateID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WorkoutSession{}
	for rows.Next() {
		var i WorkoutSession
		if err := rows.Scan(
			&i.ID,
			&i.UserProgramStateID,
			&i.WeekNumber,
			&i.DayIndex,
			&i.Status,
			&i.StartedAt,
			&i.FinishedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateWorkoutSessionStatus = `-- name: UpdateWorkoutSessionStatus :exec
UPDATE workout_sessions
SET status = ?, updated_at = ?
WHERE id = ?
`

type UpdateWorkoutSessionStatusParams struct {
	Status    string `json:"status"`
	UpdatedAt string `json:"updated_at"`
	ID        string `json:"id"`
}

func (q *Queries) UpdateWorkoutSessionStatus(ctx context.Context, arg UpdateWorkoutSessionStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateWorkoutSessionStatus, arg.Status, arg.UpdatedAt, arg.ID)
	return err
}
